### ISSUE TITLE
Deprecate janitor.patterns

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1007]
janitor.patterns is not really useful (beauty of hindsight :grin: ) , as it is simply a wrapper around `re.compile`, which a user can import and wrap

```py
from re import compile as patterns # or whatever name user prefers
import janitor
import pandas as pd

df.select_columns(patterns('\d+')
```

**Comment by ericmjl** [comment]
Blessed is the developer who deletes code!
