### ISSUE TITLE
[BUG] Unexpected mutation of original df by `sort_column_value_order`

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#1008]
# Brief Description
The `sort_column_value_order` function adds a new column `cond_order` to the original dataframe (see [here](https://github.com/pyjanitor-devs/pyjanitor/blob/9d3653f959f11150bcc9aca87476efc72affc60a/janitor/functions/sort_column_value_order.py#L55)) for implementation purposes.

But this is mutating the original dataframe in a non-expected way -- the end user shouldn't be seeing this new column since `cond_order` is only used in the internal implementation of the sorting function.

# Minimally Reproducible Code

```python
df = pd.DataFrame({
    "a1": [4, 2, 9, 12],
    "a2": ["x", "y", "z", "y"],
})
df.sort_column_value_order("a2", {"x": 3, "y": 2, "z": 1});
df

# original df now has an additional column...
   a1 a2  cond_order
0   4  x           3
1   2  y           2
2   9  z           1
3  12  y           2
```

**Comment by ericmjl** [comment]
This is the kind of thing I know how to fix easily, first dibs!
