### ISSUE TITLE
[EHN] let `filter_string` suit parameters of `Series.str.contains`

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1047]
# Brief Description

- `Series.str.contains(pat, case=True, flags=0, na=None, regex=True)`
- `filter_string(df, column_name, search_string, complement=False)`

`filter_string` is a super sugary syntax for `contains`.
`contains` has five arguements, but `filter_string` only has one arguement `search_string`.

I thought we should complete parameters of `filter string`.

# Example API

A example `filter_string` would get error result.

```python
import pandas as pd
import janitor  # noqa

df = pd.Series(["JoseChen", "Brian.Salvi"], name="Name").to_frame()

# find any '.' rows
df[df.Name.str.contains(".", regex=False)]
#           Name
# 1  Brian.Salvi

# error
df.filter_string(".")
#             Name
# 0     JoseChen
# 1    Brian.Salvi
```

**Comment by samukweku** [comment]
resolution of this should fix #1003

**Comment by Zeroto521** [comment]
Can I fix this problem?

**Comment by samukweku** [comment]
@Zeroto521 yes pls
