### ISSUE TITLE
Name fell off AUTHORS.md

### ISSUE THREAD

**Issue by robertmitchellv** [pyjanitor-devs/pyjanitor#1054]
I think this might've just been an accident or side effect of moving to Sphinx

- Currently I'm not listed on `pyjanitor/AUTHORS.md`; [this was the contribution I made](https://github.com/pyjanitor-devs/pyjanitor/commits?author=robertmitchellv)

Maybe because my name was last on the `AUTHORS.rst` file it was dropped.

- Would it be ok to re-add it to `AUTHORS.md`? [Here's where it was dropped](https://github.com/pyjanitor-devs/pyjanitor/commit/a6832d47d2cc86b0aef101bfbdf03404bba01f3e)

Thanks so much; I've been evangelizing this library far and wide and hope to contribute again soon!

❤️

**Comment by samukweku** [comment]
@robertmitchellv kindly raise a PR to include your name in the authors.md file. I have no idea why it got chucked off.

**Comment by robertmitchellv** [comment]
Will do; thanks so much @samukweku 🙌🏻
