### ISSUE TITLE
https://github.com/pyjanitor-devs/pyjanitor/blob/dev/api/functions

### ISSUE THREAD

**Issue by richlysakowski** [pyjanitor-devs/pyjanitor#1055]
# Brief Description of Fix

The hyperlink is broken to "General Functions" on the pyjanitor homepage 
It gives a 404 error, even though the URL looks complete as "https://github.com/pyjanitor-devs/pyjanitor/blob/dev/api/functions"

Click on the link to find out where it takes you...

**Quick start**
```
Installation: conda install -c conda-forge pyjanitor
Check out the collection of [general functions](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/api/functions)
```

**Comment by samukweku** [comment]
Thanks @richlysakowski ... If you have some time on you, the pyjanitor community would appreciate it if you could raise a PR to resolve this
