### ISSUE TITLE
Discussion: arguments `old_min` and `old_max` should be removed from `min_max_scale`

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1068]
```python
>>> import pandas as pd
>>> import janitor

# Use one column dataframe to avoid scaling the entire data or the column data problem

>>> df = pd.Series([0, 1, 2]).to_frame()

# use the minimum and maximum value of data

>>> df.min_max_scale()
     0
0  0.0
1  0.5
2  1.0

# Overwrite the value of data. The result seems wired for the user, but it's ok for the formula view.
# Question 1: 0 should be scaled or not? 0 is out range of [old_min 1, old_max 2].
# Question 2: I already define the new_min (0) and new_max of value. Why do there have -1?
# Question 3: The API differs from sklearn.preprocessing.MinMaxScaler

# Min-Max normalization formula
# X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
# X_scaled = X_std * (max - min) + min

>>> df.min_max_scale(old_min=1, old_max=2)
     0
0 -1.0
1  0.0
2  1.0
```

In the end, it's hard to trace the `min_max_scale` [committing history](https://github.com/pyjanitor-devs/pyjanitor/commits/dev/janitor/functions/min_max_scale.py) to know the reason why added these options.

**Comment by ericmjl** [comment]
@Zeroto521 your third question revealed a lot for me and prompted the best amount of clarity here.

If anything, I believe we should follow sklearn's API and behaviour. I'm in favour of matching the sklearn API, actually, it's much cleaner than what we have. For clarity, sklearn uses:

`MinMaxScaler(feature_range=(min_val, max_val))`

(https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)
