### ISSUE TITLE
Simpler Cython option with python type hints? 

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1096]
Cython now offers an option where python typing can be inferred from for possible speed ups. This might come in handy for some functions (conditional_join maybe?) where some performance could be obtained by moving some of the python computation to C, while avoiding the complexities of C.

**Comment by Zeroto521** [comment]
The first step may be to build a script _typing.py that could contain some common typing constants such as `column_name` and `column_name`.

**Comment by samukweku** [comment]
Yeah, just putting it out there for a more generic conversation, especially compared to numba

**Comment by samukweku** [comment]
Closing this ... Safer to contribute directly to pandas
