### ISSUE TITLE
Require pyspark minimal version is v3.2.0 to cut duplicates codes

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1110]
Since [pyspark v3.2.0](https://github.com/apache/spark/blob/5d45a415f3a29898d92380380cfd82bfc7f579ea/python/pyspark/pandas/extensions.py#L28-L64), it has contained `CachedAccessor`, `_register_accessor`, `_register_accessor`

janitor requires pyspark minimal version is v3.1.2 at present.
Compared to v3.1.2, v3.2.0 is a minor version.

https://github.com/pyjanitor-devs/pyjanitor/blob/4867b20273e99cb2f4c32278123d5c23c2ccaa67/janitor/spark/backend.py#L9-L37

Note: The pyspark in the [setup.py](https://github.com/pyjanitor-devs/pyjanitor/blob/4867b20273e99cb2f4c32278123d5c23c2ccaa67/.requirements/spark.txt#L9) file requires v3.2.1 but ci ([environment-dev.yml](https://github.com/pyjanitor-devs/pyjanitor/blob/4867b20273e99cb2f4c32278123d5c23c2ccaa67/environment-dev.yml#L41)) requires v3.1.2.

**Comment by ericmjl** [comment]
@Zeroto521 with PySpark 3.2.0 we'd be able to directly register our code on pyspark dataframes?

**Comment by Zeroto521** [comment]
> @Zeroto521 with PySpark 3.2.0 we'd be able to directly register our code on pyspark dataframes?

Yes, it could easily import 'register_dataframe_accessor' from pyspark since 3.2.0 version.

But pyjanitor still needs to keep 'register_dataframe_method'.

**Comment by ericmjl** [comment]
That's such a cool find. Thank you so much, @Zeroto521 :heart:

**Comment by ericmjl** [comment]
@Zeroto521 I can't remember, but have we added you to the core dev team, btw? Having seen your contributions and patience with the project, I think you'd be a valuable addition to the team.

**Comment by Zeroto521** [comment]
For more step, even `register_dataframe_method` could be simplified via `register_method_factory` in https://github.com/Zsailer/pandas_flavor/issues/23

**Comment by Zeroto521** [comment]
> @Zeroto521 I can't remember, but have we added you to the core dev team, btw? 

No. But I'm happy to become the core maintainer of pyjanitor project.

**Comment by ericmjl** [comment]
Cool stuff! I'm going to add you onto the dev team. Could you ping me at http://www.shortwhale.com/ericmjl? I'll also add you onto the Discord chat that we use. (It's very low volume, btw, and it's more for social chat than dev chat.)

**Comment by Zeroto521** [comment]
> Could you ping me at http://www.shortwhale.com/ericmjl?

Done.

> I'll also add you onto the Discord chat that we use. (It's very low volume, btw, and it's more for social chat than dev chat.)

The Discord service is blocked in China. So I'm not very frequently use it.
¯\_(ツ)_/¯
