### ISSUE TITLE
CI: Duplicate style checking

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1113]
I noted there are two of the same style checking CIs.

- One comes from Github Action [code-checks.yml](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/.github/workflows/code-checks.yml) file
- Another comes from Github App [.pre-commit-config.yaml](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/.pre-commit-config.yaml) file

And there has evidence to show that pre-commit.ci is better than Github Action.

![image](https://user-images.githubusercontent.com/25895405/171584327-ae550c64-66e8-4534-8296-73e52b75be34.png)
> from pre-commit.ci [official website](https://pre-commit.ci/)

**Comment by ericmjl** [comment]
Thanks for handling this, @Zeroto521! I think it's okay for us to keep both in place, as there are subtle differences between the two. The most obvious is that pre-commit.ci will also format code for us, while the Action will only check code for us. By keeping the pre-commit Action, we have a backup in case pre-commit.ci goes down. 

For that reason, I'll close this issue. However, if there is a really strong reason to remove the Action, happy to re-discuss.
