### ISSUE TITLE
replicate `select_columns` on the index

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1124]
select_columns can be adapted to index selection as well; not sure about the name though  ---> select_index/select_rows?

```py
df.select_index()
df.select_rows()
```

**Comment by ericmjl** [comment]
Some of the great work you've done, @samukweku, like incorporating `slice()`s, would be usable here too! Out of curiosity, what prompted the idea here?

**Comment by samukweku** [comment]
Thanks @ericmjl . I have come to love the flexibility/abstraction of select_columns hence the idea of extending it to rows.

**Comment by ericmjl** [comment]
Got it!

`select_rows()` would be a great addition, definitely.

I can also see us building on top of `select_columns()` and `select_rows()` to provide a `select(rows=..., columns=...)` API that then dispatches down to `select_columns()` and `select_rows()`. It would be a nicely chained API that could be more flexible than the built-in `.loc[]` calls.

**Comment by samukweku** [comment]
Yea, that would be great. Not sure of the select word though, it seems pandas has plans for that too : https://github.com/pandas-dev/pandas/issues/40322
