### ISSUE TITLE
List of general functions and their documentation isn't showing up in the documentation

### ISSUE THREAD

**Issue by DavidHinchee** [pyjanitor-devs/pyjanitor#1146]
"General Functions" link on this page doesn't open the list of general functions and their documentation:

This link: https://pyjanitor-devs.github.io/pyjanitor/api/functions/

and this link: https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions--general-functions

display same page. 

All other "API Reference" subsection links--Biology, Chemistry, Engineering, etc.--display functions & descriptions, but not the General

**Comment by Zeroto521** [comment]
I can make sure `mkdocstrings` 0.19.0 #1138 cause this.
0.19.0 is breaking changing version.

The lower version use `mkdocstrings-python-legacy` as the documentation hander.

A quickly fix this we can [`mkdocstrings-python-legacy`](https://pypi.org/project/mkdocstrings-python-legacy/) as the default handler instead of [`mkdocstrings-python`](https://pypi.org/project/mkdocstrings-python/)

As the developer said, `mkdocstrings-python` is the future.
`mkdocstrings-python-legacy` official has a note.
> WARNING: We suggest using the new handler instead: [mkdocstrings-python](https://mkdocstrings.github.io/python/).

**Comment by Zeroto521** [comment]
I know little about mkdocs, I use sphinx a lot.
I don't why functions documentation missing.

But I know how to fix this.
![image](https://user-images.githubusercontent.com/25895405/184469169-48e4801f-0113-42f0-9672-6a8290c65b93.png)
```diff
    Method chaining usage example:

-    >>> import pandas as pd
-    >>> import janitor.finance
-    >>> df = pd.DataFrame({"profit":[100.10, 200.20, 300.30, 400.40, 500.50]})
-    >>> df
-       profit
-    0   100.1
-    1   200.2
-    2   300.3
-    3   400.4
-    4   500.5
-    >>> df.inflate_currency(
-    ...    column_name='profit',
-    ...    country='USA',
-    ...    currency_year=2015,
-    ...    to_year=2018,
-    ...    make_new_column=True
-    ... )
-       profit  profit_2018
-    0   100.1   106.050596
-    1   200.2   212.101191
-    2   300.3   318.151787
-    3   400.4   424.202382
-    4   500.5   530.252978
+    ```python
+    >>> import pandas as pd
+    >>> import janitor.finance
+    >>> df = pd.DataFrame({"profit":[100.10, 200.20, 300.30, 400.40, 500.50]})
+    >>> df
+       profit
+    0   100.1
+    1   200.2
+    2   300.3
+    3   400.4
+    4   500.5
+    >>> df.inflate_currency(
+    ...    column_name='profit',
+    ...    country='USA',
+    ...    currency_year=2015,
+    ...    to_year=2018,
+    ...    make_new_column=True
+    ... )
+       profit  profit_2018
+    0   100.1   106.050596
+    1   200.2   212.101191
+    2   300.3   318.151787
+    3   400.4   424.202382
+    4   500.5   530.252978
+    ```
```

or

```diff
    Method chaining usage example:

-    >>> import pandas as pd
-    >>> import janitor.finance
-    >>> df = pd.DataFrame({"profit":[100.10, 200.20, 300.30, 400.40, 500.50]})
-    >>> df
-       profit
-    0   100.1
-    1   200.2
-    2   300.3
-    3   400.4
-    4   500.5
-    >>> df.inflate_currency(
-    ...    column_name='profit',
-    ...    country='USA',
-    ...    currency_year=2015,
-    ...    to_year=2018,
-    ...    make_new_column=True
-    ... )
-       profit  profit_2018
-    0   100.1   106.050596
-    1   200.2   212.101191
-    2   300.3   318.151787
-    3   400.4   424.202382
-    4   500.5   530.252978
+       >>> import pandas as pd
+       >>> import janitor.finance
+       >>> df = pd.DataFrame({"profit":[100.10, 200.20, 300.30, 400.40, 500.50]})
+       >>> df
+          profit
+       0   100.1
+       1   200.2
+       2   300.3
+       3   400.4
+       4   500.5
+       >>> df.inflate_currency(
+       ...    column_name='profit',
+       ...    country='USA',
+       ...    currency_year=2015,
+       ...    to_year=2018,
+       ...    make_new_column=True
+       ... )
+          profit  profit_2018
+       0   100.1   106.050596
+       1   200.2   212.101191
+       2   300.3   318.151787
+       3   400.4   424.202382
+       4   500.5   530.252978
```

**Comment by samukweku** [comment]
thanks @DavidHinchee for the observation. @Zeroto521 @ericmjl should we revert temporarily to `mkdocs-python-legacy`?

**Comment by Zeroto521** [comment]
Does Mkdocs have documentation version feature?
We always let us see latest version. But some new coming features are not in stable (released) package.
If Mkdocs owns this feature, we could easily fix it via pointing site to stable version documentation.
![image](https://user-images.githubusercontent.com/25895405/184518996-9132d8c8-6de7-43f2-be72-2564ecaee8d9.png)

**Comment by samukweku** [comment]
@Zeroto521 something like this: [link](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning)

**Comment by ericmjl** [comment]
I am pushing up a temporary fix for the docs; we will pin `mkdocstrings` to 0.18.1. In a future PR, this can be fixed up.

**Comment by samukweku** [comment]
@DavidHinchee kindly have a look now; the documentation should render completely

**Comment by DavidHinchee** [comment]
Confirmed that the decimation renders completely for me. Thanks and kudos to the development team. You’ve created a package that’s truly useful to me as a new pandas/python coder.

**Comment by ericmjl** [comment]
Thank you, @DavidHinchee, for letting us know! The positive feedback is encouraging!

**Comment by Zeroto521** [comment]
There has another reason need to set the versioning feature for the docs website. #1145
