### ISSUE TITLE
[BUG] `pivot_longer` test cases failed on pandas latest (1.4.x) passed on 1.3.x

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1154]
I found why #1143 failed on `pivot_longer`, `encode_categorical`, and `_select_column` test cases
The core reason is **the version compatibility**.
Our current test environment only tests one main pandas version 1.3.x. But the latest pandas version is 1.4.x.
https://github.com/pyjanitor-devs/pyjanitor/blob/a027753a4105c4c7ff920ba31f5afd51206cfffb/environment-dev.yml#L36

There pivot_longer method test cases failed on pandas [latest version (1.4.x)](https://github.com/pyjanitor-devs/pyjanitor/runs/7927921175?check_suite_focus=true#step:3:744), but passed on [1.3.x](https://github.com/pyjanitor-devs/pyjanitor/runs/7927901920?check_suite_focus=true#step:3:854).

Call for helping @samukweku, (I do use less about `pivot_longer` accessor, so I can't handle these problems).

- tests/functions/test_pivot_longer.py::test_names_pattern_str
- tests/functions/test_pivot_longer.py::test_names_sep
- tests/functions/test_pivot_longer.py::test_names_transform_numeric

**Comment by samukweku** [comment]
@Zeroto521 do you mind sharing the link to the error messages, so I can test, and hopefully, resolve with the actual test data  that failed?

**Comment by samukweku** [comment]
@Zeroto521 Do you have any idea about the `test_documentation_build.py` failure?

**Comment by Zeroto521** [comment]
Mkdocs and its related packages are not in environment.
