### ISSUE TITLE
broken link to contributing guidelines

### ISSUE THREAD

**Issue by asmirnov69** [pyjanitor-devs/pyjanitor#1179]
# Brief Description of Fix

from this page https://github.com/pyjanitor-devs/pyjanitor/pulls link to contributing guidelines https://github.com/pyjanitor-devs/pyjanitor/blob/352977c663fb070733df4914ecfe4afaff9e8a6d/CONTRIBUTING.md leads to some page stub

**Comment by samukweku** [comment]
Hi @asmirnov69 thanks for raising the issue. The link you shared is the pull request page, and I couldn't find the link you were referring to. Do you mind sharing the actual broken link

**Comment by asmirnov69** [comment]
this is the link which doesn't look right: https://github.com/pyjanitor-devs/pyjanitor/blob/352977c663fb070733df4914ecfe4afaff9e8a6d/CONTRIBUTING.md

it sits on [pull request page](https://github.com/pyjanitor-devs/pyjanitor/pulls) as '<u>contributing guidelines</u>' in banner '<b>First time contributing to pyjanitor-devs/pyjanitor?</b>'

**Comment by samukweku** [comment]
this is a screenshot of the pull request page, do you mind pointing out the contributing guidelines link ?
![pullrequest](https://user-images.githubusercontent.com/25709809/196555197-90d47c2d-fcc9-43c9-a9b2-d89a157d817b.png)

**Comment by asmirnov69** [comment]
mine is slightly different, broken linked marked by orange lines

<img width="1773" alt="orange-loop" src="https://user-images.githubusercontent.com/4543018/196556022-fb5bac56-e462-4240-b572-b1a2f8329d50.png">

**Comment by samukweku** [comment]
Thanks @asmirnov69 do you mind raising a PR to fix this?

**Comment by asmirnov69** [comment]
ok, i will take a look starting tomorrow. if you have any hints/description on how to fix the issue - let me know...

**Comment by samukweku** [comment]
you can create a markdown file with this [guide](https://pyjanitor-devs.github.io/pyjanitor/devguide/) and paste it in the linked page

**Comment by asmirnov69** [comment]
it is strange but issue is gone: no banner shows up anymore. Also the reason why it was happening seems to be github problem of handling md files via links. according to [Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) CONTRIBUTING.md from repo root is used in many context. Looks like I hit to one of such situation and github failed to follow symlink.

SO I will close this issue. To really fix a problem someone with knowledge of the plan around mkdocs directory should get rid of CONTRIBUTING.md symlink and replace it with content of mkdocs/devguide.md - maybe some CI job can do that. Alternative is to report the problem to github and wait for resolution - could be long wait...

**Comment by samukweku** [comment]
thanks @asmirnov69 the @pyjanitor-devs/core-devs appreciate this
