### ISSUE TITLE
[TST] Compat with macos and window, FailedHealthCheck

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1181]
This PR #1143 is almost done.
But it still left one problem.
HealthCheck always failed on macos and window system like following.

https://github.com/pyjanitor-devs/pyjanitor/actions/runs/3281183133/jobs/5402869041#step:5:2147

```python
_____________________________ test_df_key_hashable _____________________________
[gw2] darwin -- Python 3.10.6 /Users/runner/miniconda3/envs/test/bin/python

    @given(df=df_strategy())
>   def test_df_key_hashable(df):
E   hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 6 valid examples in 1.08 seconds (0 invalid ones and 4 exceeded maximum size). Try decreasing size of the data you're generating (with e.g. max_size or max_leaves parameters).
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.

tests/functions/test_expand_grid.py:40: FailedHealthCheck
```

I thought wether we could use a small size date like `max_size=10` or a small one?

https://github.com/pyjanitor-devs/pyjanitor/blob/f0c79066c3faa0762626339054692401a7b8db58/janitor/testing_utils/strategies.py#L21-L43

**Comment by Zeroto521** [comment]
I tried to use `max_size=10`.
- commit: 5e6031bdbaae02aaae93db7761828ef970668270
- workflow: https://github.com/pyjanitor-devs/pyjanitor/actions/runs/3287400352/jobs/5416533670

window all testcases passed.
macos testcases still failed. but there the failed number got cut from 29 to 15 (macos-latest, 3.10, ci/envs/latest.yaml)

**Comment by samukweku** [comment]
Is it possible to disable the health check?

**Comment by samukweku** [comment]
This [link](https://hypothesis.readthedocs.io/en/latest/healthchecks.html) could be helpful
