### ISSUE TITLE
[TST] `functions/(add_columns|conditional_join).py` scripts are not covered by test cases

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#1196]
The `codecov/project` of latest commit 3687219bbc26c577a6992e2867add79711a5bf96 on dev branch is **77.60% (-20.04%)**.

The following methods or scripts aren't covered by test cases.
Please go codecov to see [details](https://app.codecov.io/gh/pyjanitor-devs/pyjanitor/commit/3687219bbc26c577a6992e2867add79711a5bf96).

- `functions/add_columns.py::add_columns`
- `functions/conditional_join.py`

We could learn that the coverage doesn't like our thought after adding `--cov-append` option.
`pytest tests` != `pytest tests -m "turtle"` + `pytest tests -m "not turtle"`

**Comment by Zeroto521** [comment]
But that is weird. Testing logic is the same for whether it is a PR or dev branch now.
I see the PR's `codecov/project` is 97.66%, not 77.60%.

**Comment by Zeroto521** [comment]
Or another solution is that directly use `pytest tests`.
Don't split test cases into `"turtle"` and `"not turtle"` two parts.
Don't figure out the reason

**Comment by samukweku** [comment]
if i remember correctly , and correct me @ericmjl , we used the turtle because some tests were taking quite some time to run, and we needed a way to let them run without timing out?

**Comment by Zeroto521** [comment]
The aim of #1185 and #1190 these two PRs are to keep the same testing logic no matter whether it's the dev branch or a PR.

The dev branch `codecov/project` history.
- Before #1185, the dev branch used `pytest tests`, and the `codecov/project` was 97%.
- After #1185 and before #1190, the dev branch used `pytest tests -m "turtle"` + `pytest tests -m "not turtle"` but without `--cov-append`. So the `codecov/project` was  47.30%.
- After #1190, the dev branch used `pytest tests -m "turtle"` + `pytest tests -m "not turtle"` with `--cov-append`. the `codecov/project` was  77.60%.

**Comment by ericmjl** [comment]
> if i remember correctly , and correct me @ericmjl , we used the turtle because some tests were taking quite some time to run, and we needed a way to let them run without timing out?

That's almost right, @samukweku! We wanted the test suite to complete faster to minimize feedback loop timing. Without splitting, we would take ~40 minutes for all tests to pass. Now it's a maximum of 26 minutes, with a possibility of further reducing if we split out testing of the longest-running tests. Of course, the alternative is to reduce the testing time of those long-running tests.

**Comment by ericmjl** [comment]
@Zeroto521 let's look at the latest test runs. `--cov-append` generally does the right thing here.

**Comment by Zeroto521** [comment]
For a single environment is working. Speed up via splitting different parts (parallelizing test cases).
But the aim of #1143 is to set multi-environments and compat with them. So here is to parallelize multi-environments, not test cases. Splitting test cases are not working to speed up. Splitting test cases get more clear for CI.

![image](https://user-images.githubusercontent.com/25895405/201497325-5fb66093-341a-41b0-8409-a46ae8746918.png)

**Comment by Zeroto521** [comment]
I suddenly found there has an option `addopts` in pyproject.toml.
It may affect the code coverage.
https://github.com/pyjanitor-devs/pyjanitor/blob/c5ba7ef1f64ee8209e6f15e775cbcfa1a78e105d/pyproject.toml#L33-L34

**Comment by Zeroto521** [comment]
> I suddenly found there has an option `addopts` in pyproject.toml. It may affect the code coverage.
> 
> https://github.com/pyjanitor-devs/pyjanitor/blob/c5ba7ef1f64ee8209e6f15e775cbcfa1a78e105d/pyproject.toml#L33-L34

This is the reason. The code coverage is back to normal. See #1204

**Comment by Zeroto521** [comment]
this issue could be closed. It was already fixed in #1204
