### ISSUE TITLE
rename_column throw warning when column not found

### ISSUE THREAD

**Issue by Zsailer** [pyjanitor-devs/pyjanitor#123]
I (finally) had an opportunity to use pyjanitor today! 😃 I ran into the unexpected behavior...

I used `rename_column` but had a typo in my first argument (the original column name). Instead of throwing a warning or error when the column wasn't found, pyjanitor continued the cleaning chain and returned a "partially-cleaned" DataFrame. It wasn't until later in my analysis that I realized the new column name didn't exist. 

I would expect pyjanitor to throw a warning or error in this case. I could *also* see this being a deliberate design choice. For example, a user may use the same logic to clean various datasets that  share some column names but not others. In that case, they might want pyjanitor to ignore columns not found.

Was this a deliberate choice? Or should `rename_column` throw an error when the column is not found (thus, also catching typos from sloppy coders like me along the way 😉)?

**Comment by ericmjl** [comment]
@Zsailer I think you caught a bug! Great catch! Let me see what I can do here. I'll loop back soon!

**Comment by Zsailer** [comment]
👍 

I'm happy to make a PR too, if you've got a lot on your plate.
