### ISSUE TITLE
[INF] darglint is archived -> move to ruff?

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#1236]
While working on #1235, I've experienced darglint to be really slow (takes minutes to run for the `functions/pivot.py` file), and also the project has been archived as of Dec 16 2022.

https://github.com/terrencepreilly/darglint/

We should transition to using `ruff`, which also provides darglint rules.

In which case, perhaps we can also drop `flake8` in favour of ruff.

EDIT:

oops, I misremembered. darglint is not covered by ruff yet, but it's in the works. https://github.com/charliermarsh/ruff/issues/458

**Comment by ericmjl** [comment]
@thatlittleboy I am going to switch our infra over to ruff. Thanks for raising this issue, and oh my, I just realized I've really neglected our shared project for a long time. (Work has been craaaazy.)
