### ISSUE TITLE
avoid explicit copy ?

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1250]
See if it is possible to avoid copy and get more performance  - 

- `complete`
- `pivot_longer`

**Comment by samukweku** [comment]
For `complete`, there is a `pd.merge` call - pandas makes a copy within `pd.merge`; as such, there is no need for an explicit copy again.

For `pivot_longer`, the transformations are done on the columns, and Pandas creates a new Index altogether - it is safe to create a view on the original dataframe since it won't be tampered with. 

Avoid copying if it isn't required, or if some other pandas process already takes care of that 😁

**Comment by ericmjl** [comment]
@samukweku I think we can close this one, perhaps? Definitely want to thank you for handling the two PRs!

**Comment by samukweku** [comment]
Yes @ericmjl it is ok to close
