### ISSUE TITLE
[ENH] cython a subset of _range_join_indices and equi join

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1311]
- with cython 3.0 we can use python typing within cython and still get some perf gains. This would be beneficial to us within the `_range_indices` section, where we have to compare within groups. instead of broadcasting (which could be costly for large datasets) we can iterate within each group, get the earliest position and just slice to get the matches. we wouldnt need to broadcast, we can break out early, and we can get the perf of C within the for loop.

**Comment by ericmjl** [comment]
Just wondering, @samukweku, given that you've already used `numba` here, is this doable using `numba` instead of `cython`?

**Comment by samukweku** [comment]
Already have a numba implementation. Going this route with cython/rust for the specific points where there is a for loop and no cover with numpy. I have also had issues with debugging numba in some cases and also Mac/Linux environments. Also because cython/rust is precompiled I/user won't need to worry about warmup.still tentative on it considering the team's reluctance to cython/rust because of complexity.

**Comment by ericmjl** [comment]
I see! I guess that makes sense, then.

Yes, there's complexity in adding in cython or rust. Perhaps it's something for us to talk about on a call. Given your excellent work on making things performant, and coupling that with additional help we could get from an LLM to explain code, I think I'm personally less hesitant with Cython/Rust at this point -- especially seeing the rest of the Python world interact with Rust so well! (ruff, nutpie, etc.) From a maintenance standpoint, that's less of an issue now, I guess.

How much extra complexity will there be in packaging, do you think? Will we need to worry about compilers for different platforms and the likes?

**Comment by samukweku** [comment]
@ericmjl closing this... no need for cython ... The more I work with it, the more I appreciate the simplicity of pyjanitor. Any cython/rust work is better contributed upstream to pandas. Numba is good enough
