### ISSUE TITLE
Outdated version in conda forge

### ISSUE THREAD

**Issue by juanfcocontreras** [pyjanitor-devs/pyjanitor#1330]
# Brief Description

Latest version in conda-forge is 0.23.1, while the latest release in 0.26.0

**Comment by ericmjl** [comment]
hmm, thank you for the catch, @juanfcocontreras! It looks like I need to go and check the conda-forge builds. In theory, they're supposed to be auto-updating, but maybe something went wrong.

**Comment by samukweku** [comment]
Conda forge picked up the latest release :  
![Screenshot_20240920-222750](https://github.com/user-attachments/assets/e1506a71-7cd1-4394-a0bb-f86a391da5ee)

I believe it is ok to close this issue. @juanfcocontreras please feel free to reopen if this is not the case.
