### ISSUE TITLE
[ENH] Change implementation to functions.remove_columns

### ISSUE THREAD

**Issue by jk3587** [pyjanitor-devs/pyjanitor#189]
Currently `functions.remove_columns` uses `del df['col']`. Instead, this function can be an alias to [pandas.DataFrame.drop](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html) with a built-in `axis=1` and `inplace=True`.

```python
@pf.register_dataframe_method
def remove_columns(df: pd.DataFrame, columns: List):
    """
    Removes the set of columns specified in cols.

    Intended to be the method-chaining alternative to `del df[col]`.

    Method chaining example:

    .. code-block:: python

        df = pd.DataFrame(...).remove_columns(cols=['col1', ['col2']])

    :param df: A pandas DataFrame
    :param columns: The columns to remove.
    """
    for col in columns:
        del df[col]
    return df
```

Could be something like:
```python
@pf.register_dataframe_method
def remove_columns(df: pd.DataFrame, columns: List):
    return df.drop(columns, axis=1, inplace=True)
```

**Comment by dave-frazzetto** [comment]
I agree on the task, I will take the issue

**Comment by jk3587** [comment]
I totally forgot as of version 0.21.0 you can do:
```python
df.drop(columns=columns, inplace=True)
```

instead of doing `axis=1`.

**Comment by lphk92** [comment]
You don't want to use `inplace=True` though. In general it tends to be much less performant, and I think they might be dropping support for it sometime in the future.

**Comment by dave-frazzetto** [comment]
The implementation was changed. 
````inplace = True```` was not used, as not needed for this function.

I would consider to add a new issue if we want to allow the user to be able to do advanced removal of columns in a multiindex table. E.g.
````
first        bar                 baz                 foo                 qux          
second       one       two       one       two       one       two       one       two
A       0.895717  0.805244 -1.206412  2.565646  1.431256  1.340309 -1.170299 -0.226169
B       0.410835  0.813850  0.132003 -0.827317 -0.076467 -1.187678  1.130127 -1.436737
C      -1.413681  1.607920  1.024180  0.569605  0.875906 -2.211372  0.974466 -2.006747
````
the user could explicitly request to delete all the columns called "one" from the inner level.

**Comment by Zeroto521** [comment]
Done via #217
