### ISSUE TITLE
[ENH] Add a "remove_dupes()" to help chaining?

### ISSUE THREAD

**Issue by dsouzadaniel** [pyjanitor-devs/pyjanitor#209]
My proposal is to add a remove_dupes() function to the library in addition to the get_dupes() function for the following reasons: 

1. Makes way more sense to have a remove_dupes() when chaining.
2. Combines it with the reset_index() which also helps in maintaining a valid index during chaining.
3. Expose the powerful 'keep' argument which is very useful in time-based data for keeping the 'first' occurrence or keeping the 'last'/latest/updated occurrence of the duplicated record.

**UPDATE: @ericmjl , I updated the outline** 

Method outline : 

```python
@pf.register_dataframe_method
def remove_dupes(df, columns=None, keep='first'):
    """
    Removes duplicate rows on a specified list of columns followed by a index reset.

    This method (_although mainly syntactic sugar_) helps combine the pandas "drop_duplicates()" with the "reset_index()" method to help chaining. Using drop_duplicates in isolation usually results in unexpected behavior. This sugary method helps solve that issue. 

    Functional usage example:
    .. code-block:: python
        df = remove_dupes(df, columns=['column_1'])

    Method chaining example:
    .. code-block:: python
        import pandas as pd
        import janitor
        df = pd.DataFrame(...).remove_dupes(columns=['column_1'])

    :param df: A pandas DataFrame object.
    :param str/iterable columns: (optional) A column name or an iterable (list
        or tuple) of column names. Following the pandas API, this only considers
        certain columns for identifying duplicates. Defaults to using all
        columns.
    :returns: A pandas DataFrame that is deduplicated. 
    """
    df = df.drop_duplicates(subset=columns, keep=keep).reset_index(drop=True)
    return df
```

Let me know if this is a useful feature & I can add it in! 🔥 🚀  Comments!? 😄

**Comment by ericmjl** [comment]
I'd be happy to accept this PR if you explain your reasoning for this PR in the docstring. If you'd like, feel free to update your outline with a more fleshed out example, including the docstrings, so that we can critique it before you do the extra work with a PR!

**Comment by szuckerman** [comment]
Isn't `drop_duplicates` already a built-in `pandas` `DataFrame` method?

**Comment by dsouzadaniel** [comment]
It is, but as mentioned above : 

This is syntatic sugar to replace the "subset" with "columns" + adds the reset_index(drop=True) method by default ( which is usually appended to drop_duplicates ). This is meant to be a single method to do exactly that.
