### ISSUE TITLE
[ENH] Convert stock symbol to company name

### ISSUE THREAD

**Issue by chrisfs** [pyjanitor-devs/pyjanitor#366]
# Brief Description

I was thinking of a function that would either convert stock symbols to company names or create a new column of company names based on stock symbols from a different column, The only issue would be to find a stable site or api that would provide the company names in return for stock symbols and handling errors when you weren't connected to the internet. 

# Example API

```
def stock_to_name(df, symbol_column_name):
```

Before

Stock
F
O
GE

Stock2Name(DF.Stock)
Stock
Ford
Realty Income
General Motors.

**Comment by ericmjl** [comment]
There's definitely a bunch of APIs! 

I've got very little domain knowledge on finance to know which one [of these](https://www.programmableweb.com/news/96-stocks-apis-bloomberg-nasdaq-and-etrade/2013/05/22) would be most reputable. Do you have an opinion?

**Comment by chrisfs** [comment]
I don't have much on the ground experience.  If I had to make a decision right now, I would choose Bloomberg because the company is big and been around for a while. I don;t know anything about the API though. 
I sent you an email through shortwhale about a related issue.

**Comment by HectorM14** [comment]
Would it be possible to find a solution that generally didn't require an internet connection? Since it's not pulling stock quotes, and the dictionary of stock symbols is mostly stable, it'd be nice not to send a request each time.

**Comment by ericmjl** [comment]
In this case, I think caching the dictionary locally would be ideal. Doesn't have to be complicated: JSON/YAML or a sqlite database. (Actually, sqlite would be overkill, IMO!)

**Comment by szuckerman** [comment]
After a brief Google search it looks like there’s only about 4000 publicly traded companies on the NYSE/Nasdaq. 

Wouldn’t it make sense to just store this in a Pandas DataFrame instead of json or YAML? Especially cause YAML has security vulnerabilities: https://tools.cisco.com/security/center/viewAlert.x?alertId=58783

**Comment by ericmjl** [comment]
That could work too! So we'd cache the pandas DataFrame, then? I think using the feather format for caching would be awesome here, especially since it's a binary format.

**Comment by HectorM14** [comment]
Are you proposing to build this and distribute with pyjanitor, or it's
built on the user's end, with the ability to rebuild at will?

**Comment by HectorM14** [comment]
Are you proposing to build this and distribute with pyjanitor, or it's
built on the user's end, with the ability to rebuild at will?

**Comment by ericmjl** [comment]
I think the latter is the better way to approach this.

**Comment by szuckerman** [comment]
Just a thought on how to extend this:

Coming from an R background, R has a number of included datasets that are readable as a data.frame. 

Similarly, scikit-learn has a number of included datasets, but those are included as arrays but not Pandas DataFrames. 

Maybe for the submodules there could be added “informational” DataFrames? Obviously the stock names for finance, but maybe a periodic table for chemistry (I have no idea if that would be necessary) and similar ones for the others?

**Comment by ericmjl** [comment]
Ahhh, I see! Yes, we could also definitely make this part of the build pipeline, i.e. including scripts to build those dataframes as part of the CI or deployment story. 

Gives me more impetus to do the auto-deployment thing right!

**Comment by HectorM14** [comment]
I like that idea @szuckerman ! What would be some other general purpose DataFrames?

**Comment by szuckerman** [comment]
So, besides the periodic table for chemistry (which may or may not be useful for chemists - I have no idea, it’s not my field) I’m not sure what would be general purpose for biology and other sciences. 

However, what I’ve used frequently recently are ones like “country abbreviations” I.e Ireland being IE, Mexico MX, etc. Similarly, for US cities having a zip code, city, state table is sometimes useful. 

Basically these are just lookup tables to give more verbose information than is in the default. For example, if I had data that only had country abbreviations and I want to know how many of those countries use Euros as their main currency, it would be a cinch to just do a join with the lookup table that has this data stored there already. 

Obviously the size of the data should be taken into account; it’s not worth it to force everyone to download a gigantic pyjanitor package for something they won’t use. (There are some libraries that take this into account and have separate modules to download for different data people want, such as the spaCy package.)

**Comment by ericmjl** [comment]
For chemistry & biology, which are the two domains I am in right now, the periodic table mappings to atomic weights and proton numbers are definitely useful. RDKit provides the ability to compute more complicated properties on the fly. My intern @bhallaY has PR'd them into pyjanitor. 

For biologists, DNA mapping to their molecular weights is generally helpful, as is the amino acid mappings to molecular weights and isoelectric points. I definitely will be PR-ing these in shortly. 

Those few examples, in all, very tiny to construct - essentially a small dictionary that can be hard-coded, and are stable over time, given that these are fundamental properties of the chemical and biological universe :smile:.


> Obviously the size of the data should be taken into account; it’s not worth it to force everyone to download a gigantic pyjanitor package for something they won’t use. 

Definitely agree! Do you know how to enable this, @szuckerman? I'm a bit at a loss here, as I've never distributed a package that has optional downloads.

**Comment by HectorM14** [comment]
These seem like good places to start. I guess the biggest contribution will getting the packaging/distribution down, and having that in place to add more in the future as needed. How big do you imagine these files would be (in relation to pyjanitor)?

**Comment by szuckerman** [comment]
@ericmjl I think there's a few ways to serve optional data files, but the easiest would most likely be to have another package, something like `pyjanitor_datasets`. That way it gets hosted on PyPI and people can just download the package.

Another way to do it would be to host the files in a CDN (or even github) and then add a `load_data()` method to pull each file when the user wants.

**Comment by ericmjl** [comment]
Looking back on this issue, yes, definitely a good idea to host this on GitHub. I like this idea. I suggest we use @chrisfs’ original use case as a testing ground for how to host data files.
