### ISSUE TITLE
[ENH] Sort by explicitly-specified column value order 

### ISSUE THREAD

**Issue by zbarry** [pyjanitor-devs/pyjanitor#382]
For plotting, it's oftentimes desired to plot your conditions in a certain order, for example. Doing this in Pandas is kind of annoying:

```python
df['cond_order'] = df['condition'].replace({'baseline': 0, 'vehicle': 1, 'treatment': 2})
sorted_df = (
    df
    .sort_values(['genotype', 'name', 'cond_order'])
    .remove_columns('cond_order')
)
```

Implementation would include checking that the values to replace exist in the column.

**Comment by ericmjl** [comment]
@zbarry could you provide a sketch of the kind of API that you'd like seen?
