### ISSUE TITLE
[DOC] Add "missing data" viz to example notebooks

### ISSUE THREAD

**Issue by ericmjl** [pyjanitor-devs/pyjanitor#4]
This is quite important. I'd like to wrap other packages rather than invent the wheel. One possible package is to wrap [missingno](https://github.com/ResidentMario/missingno) with a user-friendly API.

**Comment by souravsingh** [comment]
I am willing to work on this.

**Comment by ericmjl** [comment]
Thanks @souravsingh! Looking forward to the PR.

**Comment by JoshuaC3** [comment]
I assume there has been no PR for this? If so, I am happy to pick this up.

My only question is, how would this differ from just using missingno itself? What added functionality would we like to see? Thanks :)

**Comment by JoshuaC3** [comment]
IMO, I prefer using the `.pipe` method on janitor function, as opposed to the `jn.DataFrame` with methods so this doesn't seem 100% natural to me. That said, I use the df.plot functionality a lot.

Also, missingno is already very easy to use,

```
import missingno as mn
mn.matrix(df)
```

This can be piped as well,

```
df.pipe(mn.matrix)
```

I will have a think about how we could extend the missing data visualisation in janitor and post back.

**Comment by ericmjl** [comment]
> This can be piped as well,
> `df.pipe(mn.matrix)`

Oooh cool stuff! I didn't realize that, actually. Thanks for sharing this!

**Comment by ericmjl** [comment]
@JoshuaC3 I think this should be shown inside an example Jupyter notebook! What do you think? We have a bunch of notebooks already present, and can show how we go from data that is dirty (and has nullity) to data that is clean and densely populated!

**Comment by dancassin** [comment]
Once the PR #6 in pyjanitor-examples is accepted, then I believe this issue can be closed as well.

**Comment by ericmjl** [comment]
Thank you, @dancassin! :tada:
