### ISSUE TITLE
[DOC] Follow PEP 257 Docstring conventions

### ISSUE THREAD

**Issue by hectormz** [pyjanitor-devs/pyjanitor#695]
# Brief Description of Fix

I propose that we follow the docstring conventions laid out in [PEP 257](https://www.python.org/dev/peps/pep-0257/).

Namely:
>One-liners are for really obvious cases. They should really fit on one line. For example:
```python
def kos_root():
    """Return the pathname of the KOS root directory."""
    global _kos_root
    if _kos_root: return _kos_root
    ...
```
and:
>Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description.
```python
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...
```

We're using Sphinx, so the docstring will have a different body, but we can still follow the formatting.

Following `pydocstyle`, the first line of the docstring should end in a period and be in imperative mood:
```python
D401: First line should be in imperative mood: 'Do', not 'Does'.

[Docstring] prescribes the function or method's effect as a command:
("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
```

Additionally, all tests should have a one line docstring that explains what the test does (for everyone's sake), and what it is testing for. We don't actually have this in the docs, but it is part of my ongoing campaign with #306 

The PR for this issue (which I am happy to do), will involve updating the docs to reflect these standards, and updating docstrings throughout the project.

# Relevant Context

- [Link to documentation page](https://ericmjl.github.io/pyjanitor/CONTRIBUTION_TYPES.html)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/docs/CONTRIBUTION_TYPES.rst)

**Comment by hectormz** [comment]
We have some variety in docstrings in `pyjanitor`, perhaps in part because this aspect isn't spelled out, or people have their own personal preferences or habits, so I welcome any discussion on this.

**Comment by ericmjl** [comment]
@hectormz this would be great. I vote in favour; how about others on the dev team?

**Comment by VPerrollaz** [comment]
I personally would welcome  a guideline on documentation, my only question is the status of examples inside the docstring? 
And maybe also the potential relationship between the test cases, the examples inside the docstring and the notebook examples.

**Comment by ericmjl** [comment]
@VPerrollaz could you clarify what you mean please? Just want to make sure your thoughts are spelled out clearly for others. Do you mean that they should be harmonized, i.e. the examples in the docstring should also be test cases?

**Comment by VPerrollaz** [comment]
My point was that in many cases the tests actually make good examples so should we encourage some kind of harmonization?
I think it is not possible to be too systematic because in some test case the setup of the dataframe is too complicated to be included.

**Comment by hectormz** [comment]
@VPerrollaz I see what you mean. Depending on the function/test, the test can make a good example. In our documentation, we could encourage that type of duplication for ease/if the author thinks it makes sense.

**Comment by hectormz** [comment]
In this issue, I was just focusing essentially on what the first line of the docstrings should be like (and that there be an empty line after). I've also been kicking some thoughts about our docs in general, so once I start that issue, there may be relevant points to be discussed there

**Comment by ericmjl** [comment]
Great discussion, sirs!

I'd like to advocate for atomic/simple changes. Even systematic ones, like those that @hectormz has done before, were done in batches (PR-by-PR). I have prior experience with that, when I helped redo about 70% of the pylab examples in matplotlib, so I don't think there's an issue with doing it this way. (Clean commit histories are generally quite nice, but I won't bend over backwards to make that a thing.)

Let's focus here on getting the docstring first line done right. @VPerrollaz, if you are feeling up for it, could you make an issue for harmonizing the examples, and propose what you think could be the right way forward? Having seen your work, I think my priors are that you'll make a well-structured suggestion that we can act on.

**Comment by VPerrollaz** [comment]
- Ok I thought @hectormz was starting a general docstring convention, sorry. 
- One of the reasons I mentioned it was that I say a few other issues related to examples, notebook and so on I will try to have a look and see if there is some underlying central issue in those cases.

**Comment by hectormz** [comment]
I'll continue with this

**Comment by hectormz** [comment]
I believe https://github.com/ericmjl/pyjanitor/blob/dev/janitor/spark/backend.py is using `Numpy` style docstrings. Should I convert them to `reStructuredText` style in the process?
