### ISSUE TITLE
Flaky notebook checks with medium_franchise.ipynb

### ISSUE THREAD

**Issue by ericmjl** [pyjanitor-devs/pyjanitor#721]
`medium_franchise.ipynb` has been flaky, and I think it's because the wikipedia page it scrapes keeps changing.

Perhaps we might need to cache the table it scrapes as a CSV file and check it into the repository.

cc: @jk3587 (I think?)

**Comment by jk3587** [comment]
Is there a separate static folder or should the csv be contained within the examples folder? I would put the csv in the same folder as the examples.

Also, is nbstripout a standard requirement now for example notebooks? Seems like the only way to pass the pre-commit hooks is to run nbstripout on the notebook.

![image](https://user-images.githubusercontent.com/37330255/91008240-87dc1980-e5a3-11ea-9936-ba4414fdcccc.png)

**Comment by ericmjl** [comment]
Hey @jk3587! Thanks for helping out here! 

On where to put the CSV file, I have a thought that should probably be taken as a starting point - what about `examples/data/`? 

On nbstripout - I'm planning to add it in as a check when we rebuild the docs using mkdocs-material, but for now, perhaps sneaking in a commit that takes out `nbstripout` from the `pre-commit-config.yaml` file might be the easiest way to go.
