### ISSUE TITLE
groupby_agg mutates dataframe

### ISSUE THREAD

**Issue by tr31zh** [pyjanitor-devs/pyjanitor#729]
# Brief Description

When using groupby_agg the source dataframe is changed
Issue may be related to https://github.com/ericmjl/pyjanitor/issues/645

# System Information

- Operating system: Windows 
- OS details (optional):  Windows Pro 19041.450
- Python version (required): 3.7
- Using pyjanitor 0.20.9 on a clean environment

# Minimally Reproducible Code

```python
import pandas as pd
import janitor

data = {
    "item": ["shoe", "shoe", "bag", "shoe", "bag"],
    "MRP": [220, 450, 320, 200, 305],
    "number_sold": [100, 40, 56, 38, 25],
}

df = pd.DataFrame(data)

print(df.head())

df.groupby_agg(by="item", agg="mean", agg_column_name="MRP", new_column_name="Avg_MRP")

print(df.head())
```

# Error Messages

The second print statement displays the new column Avg_MRP

```

```

**Comment by tr31zh** [comment]
This issue could be related to https://github.com/ericmjl/pyjanitor/issues/645

**Comment by tr31zh** [comment]
It seems that there's a dataframe copy instruction missing before creating the new column

**Comment by samukweku** [comment]
@tr31zh Thanks for the feedback. You are right; the original dataframe should not be modified. I'll have a look into this.

**Comment by samukweku** [comment]
The error is mine. Will push updates to fix this. A copy() method will be included. Thanks @tr31zh

**Comment by tr31zh** [comment]
Thanks
