### ISSUE TITLE
[DOC] Update docs to have timeseries section

### ISSUE THREAD

**Issue by loganthomas** [pyjanitor-devs/pyjanitor#742]
# Brief Description of Fix

Currently, the docs do not have a section for the timeseries module.

I would like to propose a change, such that now the docs will have details on the timerseries functions.

# Relevant Context

- [Link to documentation page](https://ericmjl.github.io/pyjanitor/reference/index.html)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/docs/reference/index.rst)

**Comment by loganthomas** [comment]
I can take this if you'd like 😄

**Comment by ericmjl** [comment]
Thanks @loganthomas! Assigning!
