### ISSUE TITLE
[DOC] Types of Contributions broken link

### ISSUE THREAD

**Issue by loganthomas** [pyjanitor-devs/pyjanitor#744]
# Brief Description of Fix

Currently, the docs have a link within `CONTRIBUTING.rst` the links **types of Contributions** to https://github.com/ericmjl/pyjanitor/blob/dev/CONTRIBUTION_TYPES.html

I would like to propose a change, such that now the docs links the above to the docs website (https://ericmjl.github.io/pyjanitor/CONTRIBUTION_TYPES.html)

# Relevant Context

- [Link to documentation page](https://github.com/ericmjl/pyjanitor/blob/dev/CONTRIBUTING.rst)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/CONTRIBUTING.rst)

**Comment by loganthomas** [comment]
@ericmjl 
Suggested labels:
- `docfix`
- `good first issue`
- `hacktoberfest-2020`

If you agree, I can label for you 😄

**Comment by ericmjl** [comment]
@loganthomas you've got admin rights, and I trust your judgment here. Please go ahead! :smile:

**Comment by Bhavna777** [comment]
I want to work on it.
