### ISSUE TITLE
[DOC] Check that all functions have a `return` and `raises` section within docstrings

### ISSUE THREAD

**Issue by loganthomas** [pyjanitor-devs/pyjanitor#745]
# Brief Description of Fix

Currently, the docstrings for some functions are lacking a `return` description and (where applicable) a `raises` description.

I would like to propose a change, such that now the docstrings for all functions within pyjanitor have a valid `return` and (where applicable) valid `raises` statements.

**Requires a look at all functions** (not just the provided examples below).

# Relevant Context

- [Good example of complete docstring - janitor.complete](https://ericmjl.github.io/pyjanitor/reference/janitor.functions/janitor.complete.html)

- Examples for missing `returns`:
  - [Link to documentation page - finance.convert_currency](https://ericmjl.github.io/pyjanitor/reference/finance.html)
  - [Link to exact file to be edited - finance.py](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/finance.py)

  - [Link to documentation page - functions.join_apply](https://ericmjl.github.io/pyjanitor/reference/janitor.functions/janitor.join_apply.html)
  - [Link to exact file to be edited - functions.py](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/functions.py)

**Comment by samukweku** [comment]
@loganthomas any ideas on how this could possibly be automated? @ericmjl I wonder if we could borrow some ideas from the `autodoc`` code.

**Comment by loganthomas** [comment]
@samukweku i love the idea of automation! Nice idea. Not sure how we could implement it off the top of my head, but open to exploring. 

👇 👀 💯 
- [darglint](https://pypi.org/project/darglint/)

**Comment by samukweku** [comment]
@loganthomas have you played with `darglint`? easy to use? i am not familiar with it

**Comment by ericmjl** [comment]
`darglint` looks like it's worth testing!

**Comment by loganthomas** [comment]
From the `darglint` docs, it looks like we have a few options:

1. We could use a `pre-commit hook`:
<img width="832" alt="Screen Shot 2020-09-14 at 18 51 18" src="https://user-images.githubusercontent.com/24984410/93149165-4844b100-f6bb-11ea-848a-21788cef0ef3.png">

2. We could run a command via CLI:
<img width="828" alt="Screen Shot 2020-09-14 at 18 51 49" src="https://user-images.githubusercontent.com/24984410/93149235-6f02e780-f6bb-11ea-86e1-ad6472cdc75c.png">

I can play around with the CLI command and report back the errors I see for the files I specified in the issue. I can also make a few fake examples and report what `darglint` returns back.

After that, perhaps we can add it as a pre-commit hook and talk about adding it to the testing pipeline?

**Comment by loganthomas** [comment]
Ok... I've played around with this a bit and I am already sold haha

# CLI Output:
- I configured a `.darglint` file with the below configs:
  - The `ignore_regex` line ignores any test functions and private methods (that start with `_`)
```
[darglint]
docstring_style=sphinx
strictness=short
ignore_regex=^(test_|_)(.*)
```
- I ran `darglint .` from the `janitor` dir and found a ton of useful information.

## A Few Good Examples
### 1.
```bash
functions.py:unionize_dataframe_categories:49: DAR401: -r TypeError
```
- This tells us that `functions.unionize_dataframe_categories()` doesn't account for a `TypeError` that it rasises in the source code (i.e. a `:raises:` section is missing in the docstring).

### 2.
```bash
functions.py:move:146: DAR401: -r ValueError
functions.py:move:170: DAR102: + int axis
functions.py:move:170: DAR102: + int or str source
functions.py:move:170: DAR102: + str position
functions.py:move:170: DAR102: + str target
functions.py:move:170: DAR101: - axis
functions.py:move:170: DAR101: - position
functions.py:move:170: DAR101: - source
functions.py:move:170: DAR101: - target
```

- This tells us that `functions.move()` doesn't account for a `ValueError` that it raises in the source code (i.e. a `:raises:` section is missing in the docstring).
- This tells us that there is an added `int axis`, `int or str source`, `str position`, and `str target` argument within the docstring.
- This tells us that `axis`, `position`, `source` and `target` aren't accounted for in the docstring.
- After reviewing the source code (below), it appears the `int` and `str` descriptors were artifacts of the docstrings prior to using type hints (and in my opinion should be removed to just have `:param axis`, `:param position`, `:pram source` and `:param target`)

```python
def move(
    df: pd.DataFrame,
    source: Union[int, str],
    target: Union[int, str],
    position: str = "before",
    axis: int = 0,
) -> pd.DataFrame:
    """
    ...

    :param df: The pandas Dataframe object.
    :param int or str source: column or row to move
    :param str target: column or row to move adjacent to
    :param str position: Specifies whether the Series is moved to before or
        after the adjacent Series. Values can be either 'before' or 'after';
        defaults to 'before'.
    :param int axis: Axis along which the function is applied. 0 to move a
        row, 1 to move a column.
    :returns: The dataframe with the Series moved.
    """"
```
### 3.
```bash
functions.py:join_apply:3542: DAR201: - return
...
finance.py:convert_currency:409: DAR201: - return
```
- This proves that the use cases that originally motivated this issue are being flagged.

## Full CLI Output
```bash
functions.py:unionize_dataframe_categories:49: DAR401: -r TypeError
functions.py:move:146: DAR401: -r ValueError
functions.py:move:170: DAR102: + int axis
functions.py:move:170: DAR102: + int or str source
functions.py:move:170: DAR102: + str position
functions.py:move:170: DAR102: + str target
functions.py:move:170: DAR101: - axis
functions.py:move:170: DAR101: - position
functions.py:move:170: DAR101: - source
functions.py:move:170: DAR101: - target
functions.py:clean_names:269: DAR101: - strip_accents
functions.py:get_dupes:441: DAR102: + str/iterable column_names
functions.py:get_dupes:441: DAR101: - column_names
functions.py:encode_categorical:456: DAR401: -r JanitorError
functions.py:encode_categorical:478: DAR102: + Hashable/iterable column_names
functions.py:encode_categorical:478: DAR101: - column_names
functions.py:label_encode:505: DAR401: -r JanitorError
functions.py:label_encode:532: DAR102: + Hashable/iterable column_names
functions.py:label_encode:532: DAR101: - column_names
functions.py:reorder_columns:624: DAR401: -r IndexError
functions.py:coalesce:714: DAR102: + bool delete_columns
functions.py:coalesce:714: DAR102: + str new_column_name
functions.py:coalesce:714: DAR101: - delete_columns
functions.py:coalesce:714: DAR101: - new_column_name
functions.py:convert_excel_date:760: DAR102: + Hashable column_name
functions.py:convert_excel_date:760: DAR101: - column_name
functions.py:convert_matlab_date:799: DAR102: + Hashable column_name
functions.py:convert_matlab_date:799: DAR101: - column_name
functions.py:convert_unix_date:837: DAR102: + Hashable column_name
functions.py:convert_unix_date:837: DAR101: - column_name
functions.py:fill_empty:852: DAR401: -r JanitorError
functions.py:expand_column:924: DAR102: + bool concat
functions.py:expand_column:924: DAR101: - concat
functions.py:concatenate_columns:947: DAR401: -r JanitorError
functions.py:deconcatenate_column:1000: DAR401: -r JanitorError
functions.py:deconcatenate_column:1000: DAR401: -r ValueError
functions.py:filter_column_isin:1482: DAR401: -r ValueError
functions.py:change_type:1561: DAR401: -r ValueError
functions.py:add_column:1613: DAR401: -r ValueError
functions.py:transform_columns:2296: DAR401: -r ValueError
functions.py:min_max_scale:2400: DAR401: -r ValueError
functions.py:min_max_scale:2456: DAR101: - column_name
functions.py:min_max_scale:2456: DAR101: - new_max
functions.py:min_max_scale:2456: DAR101: - new_min
functions.py:min_max_scale:2456: DAR101: - old_max
functions.py:min_max_scale:2456: DAR101: - old_min
functions.py:select_columns:2789: DAR401: -r NameError
functions.py:select_columns:2789: DAR401: -r TypeError
functions.py:impute:2861: DAR401: -r KeyError
functions.py:impute:2861: DAR401: -r ValueError
functions.py:also:2993: DAR102: + args, kwargs
functions.py:also:2993: DAR101: - **kwargs
functions.py:also:2993: DAR101: - *args
functions.py:find_replace:3026: DAR201: - return
functions.py:groupby_agg:3278: DAR102: + axis
functions.py:set_description:3349: DAR401: -r ValueError
functions.py:bin_numeric:3377: DAR401: -r ValueError
functions.py:drop_duplicate_columns:3453: DAR003: ~<
functions.py:shuffle:3515: DAR201: - return
functions.py:join_apply:3542: DAR201: - return
functions.py:jitter:3783: DAR401: -r TypeError
functions.py:jitter:3783: DAR401: -r ValueError
functions.py:sort_naturally:3885: DAR201: - return
functions.py:expand_grid:3960: DAR401: -r KeyError
functions.py:expand_grid:3960: DAR401: -r TypeError
functions.py:process_text:4078: DAR401: -r KeyError
functions.py:process_text:4148: DAR102: + args, kwargs
functions.py:process_text:4148: DAR101: - **kwargs
functions.py:process_text:4148: DAR101: - *args
functions.py:process_text:4148: DAR101: - string_function
functions.py:fill_direction:4181: DAR401: -r ValueError
functions.py:groupby_topk:4324: DAR401: -r KeyError
functions.py:groupby_topk:4324: DAR401: -r ValueError
functions.py:complete:4443: DAR401: -r TypeError
functions.py:complete:4443: DAR401: -r ValueError

finance.py:convert_currency:409: DAR201: - return
finance.py:inflate_currency:586: DAR201: - return

io.py:read_csvs:14: DAR201: - return
io.py:read_csvs:14: DAR401: -r JanitorError
io.py:read_csvs:14: DAR401: -r ValueError

ml.py:get_features_targets:50: DAR102: + str/iterable feature_column_names
ml.py:get_features_targets:50: DAR102: + str/iterable target_column_names
ml.py:get_features_targets:50: DAR101: - feature_column_names
ml.py:get_features_targets:50: DAR101: - target_column_names

utils.py:check:16: DAR401: -r TypeError
utils.py:check:26: DAR202: + return
utils.py:rename_kwargs:290: DAR401: -r TypeError
utils.py:rename_kwargs:301: DAR202: + return
utils.py:check_column:318: DAR401: -r ValueError
utils.py:check_column:331: DAR202: + return

chemistry.py:smiles2mol:88: DAR401: -r ValueError
chemistry.py:morgan_fingerprint:170: DAR401: -r ValueError

engineering.py:convert_units:31: DAR401: -r TypeError

math.py:log:19: DAR103:  ~error: expected str but was str, optional
math.py:sigmoid:53: DAR201: - return
math.py:sigmoid:53: DAR101: - s
math.py:logit:62: DAR401: -r RuntimeError
math.py:logit:66: DAR103:  ~error: expected str but was str, optional
math.py:probit:103: DAR103:  ~error: expected str but was str, optional
math.py:z_score:139: DAR103:  ~moments_dict: expected dict but was dict, optional
math.py:ecdf:165: DAR401: -r TypeError
math.py:ecdf:165: DAR401: -r ValueError

testing_utils/strategies.py:df_strategy:21: DAR201: - return

xarray/functions.py:clone_using:24: DAR401: -r ValueError

spark/backend.py:register_dataframe_accessor:62: DAR101: - name
spark/backend.py:register_dataframe_accessor:62: DAR201: - return
spark/backend.py:register_dataframe_method:81: DAR101: - method
spark/backend.py:register_dataframe_method:81: DAR201: - return
```

## Reference:
Error Codes
- *DAR001*: The docstring was not parsed correctly due to a syntax error.
- *DAR002*: An argument/exception lacks a description
- *DAR003*: A line is under-indented or over-indented.
- *DAR004*: The docstring contains an extra newline where it shouldn't.
- *DAR101*: The docstring is missing a parameter in the definition.
- *DAR102*: The docstring contains a parameter not in function.
- *DAR103*: The docstring parameter type doesn't match function.
- *DAR104*: (disabled) The docstring parameter has no type specified
- *DAR201*: The docstring is missing a return from definition.
- *DAR202*: The docstring has a return not in definition.
- *DAR203:* The docstring parameter type doesn't match function.
- *DAR301*: The docstring is missing a yield present in definition.
- *DAR302*: The docstring has a yield not in definition.
- *DAR401*: The docstring is missing an exception raised.
- *DAR402*: The docstring describes an exception not explicitly raised.
- *DAR501*: The docstring describes a variable which is not defined.

The number in the hundreds narrows the error by location in the docstring:

- *000*: Syntax, formatting, and style
- *100*: Args section
- *200*: Returns section
- *300*: Yields section
- *400*: Raises section
- *500*: Variables section

## Adtional notes
- We can still iignore errors in the docstring via `# noqa: <error> <argument>`
```python
def we_dont_want_a_returns_section():
  """Return the value, 3.

  # noqa: DAR201

  """
  return 3
```

```python
def a_bound_function(self, arg1):
  """Do something interesting.

  Args:
    arg1: The first argument.

  # noqa: DAR101 arg1

  """
  arg1.execute(self)
```

- If we do go the pre-commit hook route, it might be nice to try and have this run with verboosity=2 rather than default since it is a bit easier to interpret to users that aren't expecting this output:
```bash
# Easier to understand
functions.py:unionize_dataframe_categories:49: DAR401: Missing exception(s) in Raises section: -r TypeError
finance.py:convert_currency:409: DAR201: Missing "Returns" in Docstring: - return

# A bit cryptiic
functions.py:unionize_dataframe_categories:49: DAR401: -r TypeError
finance.py:convert_currency:409: DAR201: - return
```

**Comment by ericmjl** [comment]
WOWWW! Superb find, @loganthomas! Let's add that in. No pressure though, only if you have time!

**Comment by loganthomas** [comment]
I’d be happy to take this one!
