### ISSUE TITLE
Cleaning non-standard unicode characters

### ISSUE THREAD

**Issue by shantanuo** [pyjanitor-devs/pyjanitor#752]
There is a space between "in %" and it does not change to underscore like "in_%" because this is a non-breaking Latin1 (ISO 8859-1) space (xa0).

```
import pandas as pd
table_GDP = pd.read_html('https://en.wikipedia.org/wiki/Economy_of_the_United_States', match='Nominal GDP')
df  = table_GDP[0]

import janitor
df=df.clean_names(strip_underscores=True, case_type='lower')

df.columns
```

> Index(['year', 'nominal_gdp_in_bil_us_dollar', 'gdp_per_capita_in_us_dollar',
>        'gdp_growth_real', 'inflation_rate_in_percent',
>        'unemployment_in_percent', 'budget_balance_in %_of_gdp_[107]',
>        'government_debt_held_by_public_in %_of_gdp_[108]',
>        'current_account_balance_in %_of_gdp'],
>       dtype='object')

We need to add normalize class to correct this and similar issues faced by the data coming from non-standard data sources.

```
from unicodedata import normalize
def clean_normalize_whitespace(x):
    if isinstance(x, str):
        return normalize('NFKC', x).strip()
    else:
        return x
```

Reference:
https://unicode.org/reports/tr15/#Norm_Forms

**Comment by ericmjl** [comment]
Hi @shantanuo! Welcome back, it's great to hear from you again :smile:. 

I'm going to triage this issue as being ready for hacking!
