### ISSUE TITLE
Truncate long column names ?

### ISSUE THREAD

**Issue by firasm** [pyjanitor-devs/pyjanitor#753]
# Brief Description

Often when exporting CSVs from questionnaires, the column names are paragraphs, or really long strings.

I would like to propose that we add an option to `clean_names` that truncates long sentence column names to something shorter. This would be useful not just in looking at the df in a notebook, but also when renaming it. Currently my workaround is to print the column names, and then use a dictionary with existing:new column names that gets passed into the rename column method.

# Example API

```python
cleaned_df = (
    pd.read_csv('data/Learning Log #1 Survey Student Analysis Report.csv')
    .clean_names(remove_special = True, truncate_limit = 50)
    .remove_empty()
)
```

^ the tuncate_limit can be defaulted to None to avoid truncating, and a number enables the maximum number of characters in the column.

**Comment by ericmjl** [comment]
@firasm thank you for chiming in! Yes, this sounds like a neat thing to add in.

Would you like to take a stab at a contribution? We’d love to expand the contributor community, and have you join in too. If not, no worries, we’ll see who in the dev team might take interest here :smile:.

**Comment by firasm** [comment]
Thanks @ericmjl - unfortunately I don't have time to start looking at the source code (full teaching load this term!), but I can paste in my solution in the hopes that it gives someone a head start?

It's basically just a one-liner `.rename_columns({item: str(item)[0:8] for item in df.clean_names().columns})` where 8 is the number of chars that should be kept in each column name.

```
import janitor
import pandas as pd

company_sales = {
    'SalesMonth': ['Jan', 'Feb', 'Mar', 'April'],
    'Company1 - this is a really long column that has mostly useless stuff.': [150.0, 200.0, 300.0, 400.0],
    'Company2 - another exceptionally long column that has mostly useless stuff.': [180.0, 250.0, np.nan, 500.0],
    'Company3 - and finally a third column with mostly useless stuff.': [400.0, 500.0, 600.0, 675.0],
    'col1 to remove': [400.0, 500.0, 600.0, 675.0],
    'col2 to remove': [400.0, 500.0, 600.0, 675.0]
}

df = pd.DataFrame.from_dict(company_sales)

df
```
<img width="598" alt="Screen Shot 2020-09-20 at 10 45 19 AM" src="https://user-images.githubusercontent.com/2507459/93718059-78aea400-fb2e-11ea-9111-6d520e702b6a.png">

```
cleaned_df = (
    df.clean_names()
    .rename_columns({item: str(item)[0:8] for item in df.clean_names().columns})
    .remove_empty()
    .remove_columns(
        [
            "col1_to_", #would be nice if remove_columns could accept wildcard/regexp so I could do 'col1.*' ?
            "col2_to_"
        ]
    )
    .rename_columns(
        {
            "salesmon": "Month",
            "company1": "Apple",
            "company2": "Microsoft",
            "company3": "Google",
        }
    )
)

cleaned_df
```
<img width="324" alt="Screen Shot 2020-09-20 at 10 45 24 AM" src="https://user-images.githubusercontent.com/2507459/93718067-7e0bee80-fb2e-11ea-81d3-264c4478105f.png">

**Comment by ericmjl** [comment]
No worries, @firasm, totally understand! Thanks for chiming back with your implementation. We'll make sure to credit you with the implementation 😄! 

By the way, I have a feeling we've overlapped at UBC before, is this correct? I was originally an MBIM student, but eventually finished in ISCI.

**Comment by firasm** [comment]
Yes we must have! Your name/picture sounded familiar but I couldn't figure out exactly where I'd seen you. small world - very nice.

**Comment by dmi3kno** [comment]
When truncating column names, it would be nice to retain the name uniqueness. For example when `truncate_length=15` both
`really long 401 name` and `really long 401 value` become `really_long_401` and `really_long_401` which is a problem!

I suggest evaluating number of collisions and if the number of collisions is under 10, set aside 2 symbols and produce `really_long 4_1` and `really_long_4_2`. Consequently if the number of collisions is over 10 you need to set aside 3 symbols (`_dd`).
