### ISSUE TITLE
[DOC] Quick Fix to Time Series Docs

### ISSUE THREAD

**Issue by loganthomas** [pyjanitor-devs/pyjanitor#754]
# Brief Description of Fix
- Quick update to the `Time Series` section of the docs
- #746 (my PR) incorrectly left out a `timeseries.rst` file within `docs/reference`

I would like to propose a change, such that now the docs correctly represent the `Time Series` section. This will including adding a `timeseries.rst` file within `docs/reference`

**Comment by ericmjl** [comment]
I vote that we sneak this one into one of your PRs :).

**Comment by loganthomas** [comment]
I realized that I actually created a `timeseries.rst` file when working on #746 
- Within `.gitignore` there is a `docs/*` line that caused git to leave this out of the PR.
- Updated to force commit `timeseries.rst` in #741

**Comment by loganthomas** [comment]
Closed with #741
