### ISSUE TITLE
concatenate_columns adds the function of ignoring empty values

### ISSUE THREAD

**Issue by Fu-Jie** [pyjanitor-devs/pyjanitor#756]
# Problem description

When I use the function of concatenating multiple columns, I find that it does not handle null values as expected.

## This is the current output

```Python
df.concatenate_columns(["cat_1","cat_2","cat_3"],"cat",sep=",")
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>cat_1</th>      <th>cat_2</th>      <th>cat_3</th>      <th>cat</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>a</td>      <td>b</td>      <td>c</td>      <td>a,b,c</td>    </tr>    <tr>      <th>1</th>      <td>c</td>      <td>NaN</td>      <td>f</td>      <td>c,nan,f</td>    </tr>    <tr>      <th>2</th>      <td>a</td>      <td>b</td>      <td>NaN</td>      <td>a,b,nan</td>    </tr>  </tbody></table>

## Here is the output I want:

```Python
df.concatenate_columns(["cat_1","cat_2","cat_3"],"cat",sep=",",ignore_empty=True)
```
<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>cat_1</th>      <th>cat_2</th>      <th>cat_3</th>      <th>cat</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>a</td>      <td>b</td>      <td>c</td>      <td>a,b,c</td>    </tr>    <tr>      <th>1</th>      <td>c</td>      <td>NaN</td>      <td>f</td>      <td>c,f</td>    </tr>    <tr>      <th>2</th>      <td>a</td>      <td>b</td>      <td>NaN</td>      <td>a,b</td>    </tr>  </tbody></table>

**Comment by ericmjl** [comment]
Hi @Fu-Jie, thanks for pinging in! Looks like something that could be a good enhancement!

Have you made an attempt at modifying the source code to make this happen? If so, we'd love to see your contribution in; after all it's an open source project where are all welcome to contribute! If not, no worries, I'll tag this as open for hacking.

**Comment by Fu-Jie** [comment]
> Hi @Fu-Jie, thanks for pinging in! Looks like something that could be a good enhancement!
> 
> Have you made an attempt at modifying the source code to make this happen? If so, we'd love to see your contribution in; after all it's an open source project where are all welcome to contribute! If not, no worries, I'll tag this as open for hacking.

Thanks  for your reply!
The following is my modified solution on the basis of the source code. 
Sorry, my code may be poor, but it should solve the problem. 

**The problem is that I will modify the columns of the source data to fill in NA  to `""`**


```Python
@pf.register_dataframe_method
def concatenate_columns(
                df: pd.DataFrame,
                column_names: List[Hashable],
                new_column_name,
                sep: str = "-",
                ignore_empty=True) -> pd.DataFrame:
 
    if len(column_names) < 2:
        raise Exception("At least two columns must be specified")
    
    if ignore_empty:
        df[column_names] = df[column_names].fillna("")
        for i, col in enumerate(column_names):
            if i == 0:
                df[new_column_name] = df[col].astype(str)
            else:
                df[new_column_name] = (df[new_column_name] + sep +
                                       df[col].astype(str))

        def remove_empty_string(x):
            '''Remove empty strings'''
            x = [x for x in x.split(sep) if x!=""]
            x = sep.join(x)
            return x
        df[new_column_name] = df[new_column_name].transform(remove_empty_string)        
                
    else:

        for i, col in enumerate(column_names):
            if i == 0:
                df[new_column_name] = df[col].astype(str)
            else:
                df[new_column_name] = (df[new_column_name] + sep +
                                       df[col].astype(str))

    return df


```

**Comment by ericmjl** [comment]
> Sorry, my code may be poor, but it should solve the problem.

@Fu-Jie having read the code, it's not a hack at all :). If I may provide some feedback, it's possible that the code duplication can be minimized, I think, by moving the `if ignore_empty: remove_empty_string` piece right to the bottom.

If you'd be open to it, I think we'd love to officially review a PR from you that houses this addition to `concatenate_columns`! `pyjanitor` is also intended to be a training ground for new open source contributors, and we do our best to recognize all contributions made. That said, I know we're all busy, so if you don't have the bandwidth, no worries - as I mentioned above, I can leave this open for others who might want to take a stab at it!

**Comment by Fu-Jie** [comment]
> I think, by moving the `if ignore_empty: remove_empty_string` piece right to the bottom.

@ericmjl  Is it changed to something like this?
```Python
@pf.register_dataframe_method
def concatenate_columns(df: pd.DataFrame,
                        column_names: List[Hashable],
                        new_column_name,
                        sep: str = "-",
                        ignore_empty=True) -> pd.DataFrame:

    if len(column_names) < 2:
        raise Exception("At least two columns must be specified")


    df[column_names] = df[column_names].fillna("")

    for i, col in enumerate(column_names):
        if i == 0:
            df[new_column_name] = df[col].astype(str)
        else:
            df[new_column_name] = (df[new_column_name] + sep +
                                    df[col].astype(str))
    if ignore_empty:

        def remove_empty_string(x):
            '''Remove empty strings'''
            x = [x for x in x.split(sep) if x!=""]
            x = sep.join(x)
            return x
        df[new_column_name] = df[new_column_name].transform(remove_empty_string)

    return df



```

**Comment by Fu-Jie** [comment]
> If you'd be open to it, I think we'd love to officially review a PR from you that houses this addition to `concatenate_columns`!
I am happy to accept that I am a frequent user of pyjanitor. I hope it will become more powerful and easy to use.

**Comment by ericmjl** [comment]
> @ericmjl Is it changed to something like this?

@Fu-Jie yep, that's what I was thinking of!

> I am happy to accept that I am a frequent user of pyjanitor. I hope it will become more powerful and easy to use.

Looking forward to seeing your PR :).

**Comment by farhanreynaldo** [comment]
Hi @ericmjl, may I open the PR for this issue? Would really love to contribute to this library.

**Comment by ericmjl** [comment]
@farhanreynaldo yes, please go ahead!
