### ISSUE TITLE
Add pipenv installation guide to docs, specifying to allow prereleases

### ISSUE THREAD

**Issue by evan-anderson-ts** [pyjanitor-devs/pyjanitor#763]
# Instructions for how to install pyjanitor via pipenv

Some folks might use pipenv for environment management. The recent update requires a prerelease dependency (black, as mentioned in [760](https://github.com/ericmjl/pyjanitor/issues/760)). I'd like to update the installation page of the documentation so that it A) includes pipenv installation and B) let's users know that they need to allow prereleases.

Something to the effect of : 
>Installation of `pyjanitor` through pipenv requires you to allow prereleases:
>```bash
>pipenv install --pre pyjanitor
>```

# Relevant Context

- [Installation page](https://pyjanitor.readthedocs.io/installation.html)
- [README (I assume this is the source of the installation page?)](https://github.com/ericmjl/pyjanitor/blob/dev/README.rst)

**Comment by ericmjl** [comment]
Hey @evan-anderson! Thanks for chiming in! Happy to accept a PR that makes this happen :smile:. Could I assign this to you?

**Comment by evan-anderson-ts** [comment]
@ericmjl Sounds good! Happy to take care of it.
