### ISSUE TITLE
Add Openpyxl to list of libraries in the environment_dev.yml

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#772]
xlrd is currently unmaintained, and causing some issues while reading an excel file in one of the tests (test_convert_excel_date.py). I propose adding `openpyxl` to the environment_dev, as it is a good alternative, can read xlsx files and is still maintained.

**Comment by hectormz** [comment]
Reading the excel file in the #771 PR is handled by `pandas`, which in turn uses `xlrd`. I don't think adding `openpyxl` to our dependencies will fix the problem, and we should look more deeply into what is happening.

**Comment by samukweku** [comment]
@hectormz In pandas, you can change the engine argument to use `openpyxl` instead of `xlrd`. The errors I noticed were related to xlrd. I may be wrong. I replied to your other comments.
