### ISSUE TITLE
Add extra functionality to `rename_columns`

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#785]
# Brief Description

It would be nice if we could extend the  [rename_columns](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.rename_columns.html#janitor.rename_columns) method to allow dynamic replacement of columns, beyond passing a dictionary. It will take the same functionality as pandas' [rename](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html) method, which it is built on, and also be able to work on a subset of columns. If it is acceptable, option of ``kwargs`` would look nice.
# Example API

```python
data = dict(x=[1], y=[2], double_x=[2], double_y=[4])
df = pd.DataFrame(data)

    x  y  double_x  double_y
 0  1  2    2        4
```
Convert all to lower case - we cant do that with [rename_columns](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.rename_columns.html#janitor.rename_columns) , but we can with pandas' [rename](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html):

```python
df.rename(columns = str.upper)

        X	Y	DOUBLE_X	DOUBLE_Y
0	1	2	2	         4
```
Suggested solution would be to add a function argument to [rename_columns](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.rename_columns.html#janitor.rename_columns):

```python
# this will apply to all the columns
df.rename_columns(func = str.upper)

        X	Y	DOUBLE_X	DOUBLE_Y
0	1	2	2	         4
```
We can also modify a subset of the columns :

```python

# single column
df.rename(columns=lambda col: col.replace("x", "stuff"))

	stuff	y	double_stuff	double_y
0	 1	2	      2	        4

# proposed equivalent in rename_columns:
df.rename_columns(func = lambda col: col.replace("x", "stuff"))

# changes to multiple columns
df.rename(columns=lambda x: x.upper() if x.startswith("double") else x)

        x	y	DOUBLE_X	DOUBLE_Y
0	1	2	2	         4

# proposed equivalent in rename_columns:
df.rename_columns(func = lambda x: x.upper() if x.startswith("double") else x)
```

And the kwargs option for one-to-one renaming (function should be able to accept kwargs or dicts, with dicts staying as first choice):

```python

df.rename_columns(old_column_name =  "new_column_name")

```

The other extreme would probably be to deprecate `rename_columns`

**Comment by nvamsikrishna05** [comment]
@samukweku Is this being worked on ? If not, I will pick it up.

**Comment by samukweku** [comment]
@nvamsikrishna05 pls go ahead
