### ISSUE TITLE
[ENH] Function that removes constant columns

### ISSUE THREAD

**Issue by ericmjl** [pyjanitor-devs/pyjanitor#788]
Example from @CihanSoylu:

```python
def drop_constant_columns(df):
    """
    Finds and drops the constant columns from a Pandas data frame
    
    Parameters
    ----------
    df : pd.DataFrame
        The Pandas data frame.
    
    Returns
    -------
    pd.DataFrame
        The Pandas data frame with the constant columns dropped.
    """
    # Find the constant columns
    constant_columns = []
    for col in df.columns:
        if len(df[col].unique()) == 1:
            constant_columns.append(col)
    
    # Drop constant columns from df and return it
    return df.drop(labels = constant_columns, 
                   axis = 1
                  )
```

**Comment by samukweku** [comment]
@ericmjl , @CihanSoylu, do you mind adding an example for this function

**Comment by fireddd** [comment]
import pandas as pd
import janitor
data_dict = {
    "a": [1, 1, 1] * 3,
    "Bell__Chart": [1, 2, 3] * 3,
    "decorated-elephant": [1, 1, 1] * 3,
    "animals": ["rabbit", "leopard", "lion"] * 3,
    "cities": ["Cambridge", "Shanghai", "Basel"] * 3
}

example_dataframe = pd.DataFrame(data_dict)
#print(example_dataframe)
def drop_constant_columns(df):
    """
    Finds and drops the constant columns from a Pandas data frame
    
    Parameters
    ----------
    df : pd.DataFrame
        The Pandas data frame.
    
    Returns
    -------
    pd.DataFrame
        The Pandas data frame with the constant columns dropped.
    """
    # Find the constant columns
    constant_columns = []
    for col in df.columns:
        if len(df[col].unique()) == 1:
            constant_columns.append(col)
    
    # Drop constant columns from df and return it
    return df.drop(labels = constant_columns, axis = 1)
drop_constant_columns(example_dataframe)
this outputs:->
<html>
<body>


Bell__Chart | animals | cities
-- | -- | --
1 | rabbit | Cambridge
2 | leopard | Shanghai
3 | lion | Basel
1 | rabbit | Cambridge
2 | leopard | Shanghai
3 | lion | Basel
1 | rabbit | Cambridge
2 | leopard | Shanghai
3 | lion | Basel


</body>
</html>
So 
all the columns with constant values are dropped as expected? Is my understanding correct?

**Comment by ericmjl** [comment]
@fireddd you have the example done right :smile:

**Comment by fireddd** [comment]
So what the next step here? Add this to functions.py and setup a test for it.

**Comment by ericmjl** [comment]
That is right, looking forward to reviewing your PR!
