### ISSUE TITLE
Duplicate Columns in some cases with `select_columns`

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#789]
# Brief Description

`select_columns` sometimes returns duplicate columns, especially when using the `*` symbol. I believe only unique columns should be returned.

# System Information
- Linux OS (Ubuntu 20.04)
- pyjanitor 0.20.10
- python 3.9

# Minimally Reproducible Code

 ```python
df = pd.read_csv("iris.csv")
df.head()

	sepal_length	sepal_width	petal_length	petal_width	species
0	5.1	   3.5	           1.4	           0.2	       setosa
1	4.9	   3.0	           1.4	           0.2	       setosa

df.select_columns(["petal*", "*width"]).head(2) # select columns that start with petal or end with width

petal_length | petal_width | sepal_width | petal_width
1.4 | 0.2 | 3.5 | 0.2
1.4 | 0.2 | 3.0 | 0.2

# petal_width is repeated twice.
```

**Comment by ericmjl** [comment]
This is a good catch, @samukweku! I think the simple fix here is to call on `df.drop_duplicate_columns()` inside `select_columns()`. Before we go to a PR for this one, is there a case where dropping duplicate columns might not be desirable?

**Comment by samukweku** [comment]
@ericmjl `drop_duplicate_columns` fixes it. However, I feel that if we make the changes and include slicing, and possibly regex options, then it would be best to adapt it to the existing for loop within `select_columns`. Also feel it should be possible to accept a string if it is just one column that will be selected.  Also avoid copying the dataframe twice 😁

Another important part which I feel keen about is I can port it into any function that requires column selection. That will significantly reduce many checks for column selections and gymnastics because we have one function that takes care of that already. It also allows reusability, and gives power/flexibility in terms of column selection. This part is significantly inspired by how dplyr allows consistent column selections in various functions. Makes it seamless.

While on the topic, does it make sense to add a level argument, if the columns are a multiindex?

**Comment by ericmjl** [comment]
That sounds amazing, @samukweku! I especially like the idea of targeting `select_columns()` as a function that lives closer to the primitive level for any thing that requires column selection. Let's go with it.

Level sounds like a good idea as well. Let's go with it!

Do you have a plan? Is there a way I can chip in, for example, if there's a piece that seems a bit substantial that you'd like a second pair of hands working on it?

**Comment by samukweku** [comment]
@ericmjl , I have the plan in my head  :grinning: I was spending too much time trying to find out how Pandas implemented the slicing functionality in ``loc``; however, I have found a way to resolve that. I will try and build out something and then share it with you.

**Comment by samukweku** [comment]
closing this as #790 fixes this.
