### ISSUE TITLE
KeyError from pivot_longer

### ISSUE THREAD

**Issue by tdhock** [pyjanitor-devs/pyjanitor#836]
# Brief Description
When I ran pivot_longer without giving column_names, I got a KeyError, which was not helpful, nor documented on the pivot_longer man page, https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.pivot_longer.html#janitor.pivot_longer
I expected a more informative error message, or at least for this error to be documented.

# System Information

- Operating system: /Linux/  
- OS details (optional):  ubuntu 20.4
- Python version (required): 3.7.6

# Minimally Reproducible Code
```
import pandas as pd
import janitor
d=pd.DataFrame({"Petal.Width":[1], "Sepal.Width":[2], "Petal.Length":[3], "Species":"setosa", "Sepal.Length":[4]})
d.pivot_longer(column_names = ["Petal.Width", "Sepal.Width","Petal.Length","Sepal.Length"], names_pattern="(.*)[.](.*)", names_to=["part", "dim"])
d.pivot_longer(names_pattern="(.*)[.](.*)", names_to=["part", "dim"])
```

# Error Messages

output I got:
```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> import pandas as pd
>>> import janitor
>>> d=pd.DataFrame({"Petal.Width":[1], "Sepal.Width":[2], "Petal.Length":[3], "Species":"setosa", "Sepal.Length":[4]})
>>> d.pivot_longer(column_names = ["Petal.Width", "Sepal.Width","Petal.Length","Sepal.Length"], names_pattern="(.*)[.](.*)", names_to=["part", "dim"])
  Species   part     dim  value
0  setosa  Petal   Width      1
1  setosa  Sepal   Width      2
2  setosa  Petal  Length      3
3  setosa  Sepal  Length      4
>>> d.pivot_longer(names_pattern="(.*)[.](.*)", names_to=["part", "dim"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tdhock/teaching/regex-tutorial/janitor_bug.py", line 5, in <module>
    d.pivot_longer(names_pattern="(.*)[.](.*)", names_to=["part", "dim"])
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/pandas_flavor/register.py", line 29, in __call__
    return method(self._obj, *args, **kwargs)
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/janitor/functions.py", line 5775, in pivot_longer
    ignore_index,
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/janitor/utils.py", line 1475, in _computations_pivot_longer
    names_pattern=names_pattern,
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/janitor/utils.py", line 1351, in _pivot_longer_extractions
    mapping.loc[:, group] = mapping.groupby(".value").cumcount()
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/pandas/core/frame.py", line 6525, in groupby
    dropna=dropna,
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 533, in __init__
    dropna=self.dropna,
  File "/home/tdhock/.local/share/r-miniconda/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 786, in get_grouper
    raise KeyError(gpr)
KeyError: '.value'
>>> 
```

**Comment by ericmjl** [comment]
Hi @tdhock! Thank you for raising this bug! 

I think it's reasonable to expect that if names_pattern is provided while no column names are provided, then we are searching amongst all of the columns. Perhaps the fix here could be a conditional inside the function that says, "if names_pattern is provided and column_names is not, then set column_names to be the set of all column names in the dataframe".

Nerd sniping @samukweku here for a second opinion - is my understanding correct here, and does the solution sound reasonable? Or is there some place it should be improved?

**Comment by samukweku** [comment]
Thanks for the nerd sniping @ericmjl :smiley:

Hi @tdhock Thanks for the observation ... more feedback/stress tests are welcome - it will definitely help to improve the library.

Could you try the `dev` version (it has not been released yet) and see if this error persists?  When I run your code, I get a `Value Error`:

```python
ValueError: 
                The regular expression in ``names_pattern``
                did not return all matches.
                Kindly provide a regular expression that
                captures all patterns.
```

I suspect the error may be because of the `Species` column, which does not match the provided pattern. If you run it with `Species` dropped, it works fine:

```python
d.drop(columns='Species').pivot_longer(names_pattern="(.*)[.](.*)", names_to=["part", "dim"])

    part     dim  value
0  Petal   Width      1
1  Sepal   Width      2
2  Petal  Length      3
3  Sepal  Length      4
```

If you've got some time, you could install the `dev` version and see if the error persists. If there are more errors, kindly point them out; I'll look at them and hopefully fix them or add clear error messages.

Thanks again.
