### ISSUE TITLE
Documentation no longer available!

### ISSUE THREAD

**Issue by adalseno** [pyjanitor-devs/pyjanitor#869]
# Brief Description

Hi, the docs are no longer available!
https://pyjanitor.readthedocs.io/

**Comment by samukweku** [comment]
Hi @adalseno. Apologies for the inconvenience. kindly visit this page https://pyjanitor-devs.github.io/pyjanitor/. Pyjanitor is not using readthedocs any more but github pages.

**Comment by ericmjl** [comment]
@adalseno I'm going to close this issue as I believe we have resolved it.
