### ISSUE TITLE
[ENH] `expand_column` function should set `sep` default is `|`

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#876]
# Brief Description

Compare to `pandas.Series.str.get_dummies` and `janitor.expand_column` definition.

```python
    def expand_column(
        df: pd.DataFrame, column_name: Hashable, sep: str, concat: bool = True
    ) -> pd.DataFrame:
```

https://github.com/pandas-dev/pandas/blob/5f648bf1706dd75a9ca0d29f26eadfbb595fe52b/pandas/core/strings/accessor.py#L1971

```python
    def get_dummies(self, sep="|"):
```

`get_dummies`'s `sep` parameter default is `|`.
`expand_column`'s `sep` parameter requires the user to input.
And `expand_column` is a sugary syntax of `get_dummies`.

I always forget to add sep when I use this function.  So the result would get a `TypeError`: missing 'sep'.
Why not set `sep` to `|`, same parameter to `get_dummies`?

# Example API

From

```python
    def expand_column(
        df: pd.DataFrame, column_name: Hashable, sep: str, concat: bool = True
    ) -> pd.DataFrame:
```

to

```python
    def expand_column(
        df: pd.DataFrame,
        column_name: Hashable,
        sep: str = "|",
        concat: bool = True,
    ) -> pd.DataFrame:
```

**Comment by samukweku** [comment]
Not a bad idea @Zeroto521. Let's wait for others to chime in. You could also create a PR for this
