### ISSUE TITLE
Speed up pytest

### ISSUE THREAD

**Issue by Zeroto521** [pyjanitor-devs/pyjanitor#881]
# Brief Description

When I do local tests, I find there only use single core to test.
That causes **so low**.
To speed up we could patch some commands such as `-n`.

# Example API

Please modify the example API below to illustrate your proposed API, and then delete this sentence.

From

https://github.com/pyjanitor-devs/pyjanitor/blob/53c86113b62d3245937c5596332f262172d916bc/Makefile#L21-L23

to

```Makefile
 test:
 	@echo "Running test suite..." 
 	pytest -v -n auto --color=yes
```

**Comment by ericmjl** [comment]
I like the idea, thank you for raising it, @Zeroto521! Would you like to do a PR for this one? It would require pytest-xdist to be installed, do we have that package in the environment spec files?
