### ISSUE TITLE
Moving to MkDocs from Sphinx

### ISSUE THREAD

**Issue by ericmjl** [pyjanitor-devs/pyjanitor#894]
## Introduction

I would like to propose that we move our docs building system to MkDocs. 

Here is why.

While Sphinx is very powerful and contains lots of features, it is also very complex. In addition, the tooling surrounding Sphinx is such that we might forget an incantation somewhere and end up with a situation, not unlike our last docs push, where the examples disappeared.

By contrast, MkDocs is much simpler and yet also easily extensible with substantially less complexity baked into it. With MkDocs, we primarily write docs in Markdown, which is (1) much more straightforward than RST syntax and (2) much better known than RST syntax.

I have hesitated to change our current docs because of the potential need to go deep into Sphinx's internals to make things happen. I've kind of lost track of the number of times I have thought of modifying something about the docs build system only to back off because I wasn't sure I'd have the confidence to finish the change in a timely fashion.

Additionally, as witnessed by our recent v0.21.1 release, I think I missed some special incantation that was not set correctly in the docs build pipeline, thus missing out on all of the example Jupyter notebooks. By contrast, `mkdocs` convention demands that everything related to configuration goes into a single config file, `mkdocs.yml`, which serves as a single source of truth for the `mkdocs build` or `mkdocs serve` commands.

## How would the change proceed?

Here, I'll outline how I think we would proceed and what parts of the MkDocs ecosystem we will use.

Our docs consist of:

1. Written prose
1. API reference
2. Executable Jupyter notebooks

Written prose maps to raw Markdown files built by the base MkDocs system. Therefore, the original RST files are relatively simple to convert, albeit a bit manual - we'd have to go in and manually change the RST docs into Markdown.

The API reference gets built by an extension called [`mkdocstrings`](https://mkdocstrings.github.io). Most of what we already have, in the form of Sphinx-style docstrings, is parse-able with `mkdocstrings`. We would change the examples to use triple-backtick syntax rather than Sphinx docs' code block syntax.

Executable Jupyter notebooks get handled by an extension called [`mknotebooks`](https://github.com/greenape/mknotebooks). I've made a PR into there that enables support for the one-click opening of a rendered Jupyter notebook inside Binder.

For themes, we could use [`mkdocs-material`](https://squidfunk.github.io/mkdocs-material/) or we could go with [other themes listed on the Wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes). 

I propose that we use a separate branch (named `mkdocs`) where we target all docs changes. We can take advantage of PR previews to make sure that all of the docs are building correctly. Anyone interested can help chip in with PRs to the `mkdocs` branch made from the `mkdocs` branch. We should also add automation to merge all changes from `dev` into `mkdocs`.

## What would we gain and lose by moving to MkDocs?

The most significant gains that I see are simplicity and ease of maintenance. 

We configure MkDocs by a single configuration file - `mkdocs.yml`, which has extensive documentation itself. Because MkDocs targets Markdown as its primary markup syntax, it's a lot easier to write and modify docs. For long-term maintenance, it makes things much easier as well. By switching to MkDocs, I think we will find ourselves catching issues with docs builds much fewer times than we otherwise would with Sphinx. 

I've found the MkDocs ecosystem to be much shallower and hence easier to debug. Furthermore, ergonomically, it has what I think is a Goldilock's-level of sophistication via extensions and ease-of-use. Thus, in explaining to newcomers, new maintainers, and sprint participants about where to look for what configuration, things are much more easily done with `mkdocs` than with Sphinx. 

Intersphinx is something that I think we use. Its functionality is available in `mkdocstrings`, but that functionality isn't yet documented properly. (See [this PR](https://github.com/mkdocstrings/mkdocstrings/pull/287) for more details.) At first, I thought this would be the most significant thing we'd miss out on, but now that I've done some cursory internet searches, I'm happy that there's a way to preserve intersphinx functionality.

This last point applies equally to Sphinx and MkDocs, though I feel much more confident in getting it right with MkDocs than with Sphinx: We can configure our dev containers to fire up the docs server inside the container automagically!

## How do we proceed?

Let's take a vote after we have a bit of discussion here. Let's use this post as the source of truth for our votes: :heart: for let's go with MkDocs, :tada: for let's go with Sphinx. You can vote for both if you're ambivalent. 

For discussion, please chime in below as well.

I will also limit the discussion to only us maintainers, as I don't think it's relevant for others.

**Comment by hectormz** [comment]
I usually support not fixing something that is not broken. But I also am not comfortable with Sphinx and I always find myself hoping that I'm following someone else's template correctly. I support switching to MkDocs if more maintainers will be more comfortable with it, and we can attract more contributors with the change. Given this proposal, I would opt for switching if it makes sense, but I did not feel strongly enough to bring up this issue on my own. If everyone wants to continue with Sphinx, that works for me.
