### ISSUE TITLE
Broken scipy dependency on fresh install

### ISSUE THREAD

**Issue by mattinbits** [pyjanitor-devs/pyjanitor#895]
# Brief Description

When installing pyjanitor with pip and trying to import it, an error about missing scipy is encountered.

# System Information

- Operating system: 
- OS details (optional): Ubuntu Linux 20.04 (WSL)
- Python version (required): 3.8.10

# Minimally Reproducible Code

`pip install pyjanitor`

followed by, in python:

`import janitor`

# Error Messages

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import janitor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matt/janitor_test/env/lib/python3.8/site-packages/janitor/__init__.py", line 7, in <module>
    from .functions import *  # noqa: F403, F401
  File "/home/matt/janitor_test/env/lib/python3.8/site-packages/janitor/functions.py", line 37, in <module>
    from scipy.stats import mode
ModuleNotFoundError: No module named 'scipy'
```

**Comment by samukweku** [comment]
Thanks @mattinbits, one workaround could be to pip install scipy then reinstall pyjanitor. Pinging @loganthomas @ericmjl @Zeroto521 : seeking your expertise on this

**Comment by loganthomas** [comment]
I can confirm this behavior. I started with a fresh (empty) conda env and installed `pyjanitor`. The same `ModuleNotFoundError` for `scipy` occurs:

```
$ conda create --name pyjan-test-env python --no-default-packages

$ conda activate pyjan-test-env

$ conda activate pyjan-test-env

$ pip install pyjanitor

$ pip install ipython
```

```python
>>> import janitor
Traceback (most recent call last):
  File "<ipython-input-2-d6fdb275fe3c>", line 1, in <module>
    import janitor
  File "/Users/logan/opt/anaconda3/envs/pyjan-test-env/lib/python3.9/site-packages/janitor/__init__.py", line 7, in <module>
    from .functions import *  # noqa: F403, F401
  File "/Users/logan/opt/anaconda3/envs/pyjan-test-env/lib/python3.9/site-packages/janitor/functions.py", line 37, in <module>
    from scipy.stats import mode
ModuleNotFoundError: No module named 'scipy'
```

Will get with other devs and look into this...

**Comment by loganthomas** [comment]
@ericmjl This issue **does not** occur when installing `pyjanitor` via `conda install pyjanitor -c conda-forge`

Wondering if there is something up with `scipy` as a dependency elsewhere. We don't explicitly list it as a requirement I believe in `pyjanitor`.

**Comment by Zeroto521** [comment]
> I can confirm this behavior. I started with a fresh (empty) conda env and installed `pyjanitor`. The same `ModuleNotFoundError` for `scipy` occurs:

Install via pip, the core problem is that `pyjanitor` misses `scipy` in here.

https://github.com/pyjanitor-devs/pyjanitor/blob/7360387dbee094a341483ee22dab2ab4394e702a/.requirements/base.in#L1-L7

Let us see the package dependencies links.

`pyjanitor` requires three packages:
- `natsort`: requires [nothing](https://github.com/SethMMorton/natsort/blob/master/setup.py)
- `pandas_flavor`: requires [`pandas` and `xarray`](https://github.com/Zsailer/pandas_flavor/blob/4cc6cbcc20028bf51debc181bbc51cb7c864767c/setup.py#L86)
- `multipledispatch`: requires [`six`](https://github.com/mrocklin/multipledispatch/blob/880e700c6fd5c17a4cd0fc0f14ec3c1fbf4255b7/setup.py#L12)

Let go deep.

`pandas` requirements are complicated. But we could easily get by typing `pip show pandas`:
- `pytz`
- `numpy`
- `python-deteutil`

From above, we could see there are no `scipy`.

**Comment by ericmjl** [comment]
@samukweku @loganthomas @Zeroto521 thanks for helping out here. I think we should include scipy as an explicit dependency and then cut a patch release to resolve this issue asap. This is because we explicitly import scipy modules inside pyjanitor. I will handle this one.

**Comment by ericmjl** [comment]
Alrighty, y'all, @samukweku & @loganthomas I'd like to at least make sure one of you two have approved this PR before we merge: https://github.com/pyjanitor-devs/pyjanitor/pull/896

**Comment by ericmjl** [comment]
@mattinbits the bots are building. I just cut a patch release. Thanks for notifying us of this issue!

**Comment by mattinbits** [comment]
Thank you! Loving the quick turnaround 👍

**Comment by ericmjl** [comment]
Our pleasure. This one turned out to be a simple fix. Thanks again for letting us know, @mattinbits :smile:
