### ISSUE TITLE
Implement tidyxl for Excel files

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#929]
# Brief Description

I would like to propose an implementation of [tidyxl](https://cran.r-project.org/web/packages/tidyxl/vignettes/tidyxl.html) within Pyjanitor for non tabular data in Excel files.

The idea is to read in the Excel file, if it cannot be handled easily with Pandas because of the non tabular nature of the data; [tidyxl](https://cran.r-project.org/web/packages/tidyxl/vignettes/tidyxl.html) in R represents each cell in its own row, where it describes the cell’s address, value and other properties. The data can then be wrangled with Pandas/Pyjanitor in a vectorized fashion.

There is a [cookbook](https://nacnudus.github.io/spreadsheet-munging-strategies/case-studies.html) that shows the advantages of this approach. I feel it might be a way to ease wrangling Excel data in python, especially for non tabular data.

**Comment by ericmjl** [comment]
This looks like a neat idea, @samukweku!
