### ISSUE TITLE
Read in Data From the command line into a Pandas DataFrame

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#945]
I would like to propose reading data from the command line into a Pandas DataFrame. This can come in handy when processing large files, where the pre-filtering step is done on the command line (`grep/sed/...`) before pulling into Pandas. This can be handy, efficient and avoid loading all the data into Pandas before processing. Inspiration for this is from R's data.table [fread](https://github.com/Rdatatable/data.table/wiki/Convenience-features-of-fread)

# Example API

```python
# transform only one column, while creating a new column name for it.
df.read_cmd(command line)
# filter for specific rows before reading into Pandas
df.read_cmd("grep -v TRIAL sum_data.txt")
# unzip file with command line before reading into Pandas
df.read_cmd('unzip -cq mtcars.csv.zip')
# can even combine several command lines
# even concatenate multiple files within the command line
# before reading into Pandas (possibly avoid concat's memory overhead)
# Unix is battle tested and performant
df.read_cmd('cat *dat.gz | gunzip | grep -v "^Day"')
```
Links:
-[fread cmd pydatatable](https://op8867555.github.io/posts/2017-10-13-use-your-unix-toolbox-with-pandas.html)
-[pandas bash fu](https://op8867555.github.io/posts/2017-10-13-use-your-unix-toolbox-with-pandas.html)

**Comment by ericmjl** [comment]
Wow, that's _quite_ the API!

Let me think, underneath the hood, it looks like the command would end up using `subprocess.run()` or `subprocess.Popen`. It'd be like this block from [this blog](https://op8867555.github.io/posts/2017-10-13-use-your-unix-toolbox-with-pandas.html) that you linked, @samukweku:

```python
import pandas as pd
from subprocess import Popen, PIPE

with Popen('cat bigdata.csv | grep WHAT_I_CARE_ABOUT | some_transformations',
           shell=True,
           stdout=PIPE) as process:
    df = pd.read_csv(process.stdout)
```

**Comment by Nalmeder** [comment]
In my senior year of undergrad I made an API to filter out large .csv files in C, which seems tangentially related to this. I could try to repurpose some of that old code and use Eric's suggestion to try and get the ball rolling on this if you'd like @samukweku (though if you'd rather tackle this one yourself, by all means save me the time)

**Comment by samukweku** [comment]
@BaritoneBeard hi… pls give it a go. I’m assuming that the code reads from the shell? Or does it do sth different, as it looks like sth that focuses on csv files? Maybe a bit of a sample of what it does? Either ways I think it would be a great addition to the library. So, pls, IMO, kindly submit a PR for this.

**Comment by Nalmeder** [comment]
@samukweku The code from my undergrad took a very large excel sheet (the U.S. Census), extracted all of the relevant columns and put those into an SQL database, which could then be queried in any way the user would like. So rather than hard coding a specific excel sheet and creating a SQL database, here I would take the file that was chosen in the cli (sys.argv[1] ) and query it according to argv[2], argv[3] ... argv[x] then create a dataframe from the result. 


Ideally: ``` python3 filename.py 'grep -v TRIAL sum_data.txt' ```
would run filename.py, which should contain something like ``` df.read_cmd(sys.argv[2]) ```


Obviously with all relevant error catching, and edge cases addressed as they come up, etc.

**Comment by samukweku** [comment]
Sweeet … a PR with usage examples 😁😁
