### ISSUE TITLE
Example of groupby_agg shows wrong output

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#963]
# Brief Description of Fix

Currently, the docs for `groupby_agg` uses `new_column_name='count'` but the result shown in the docs has column name 'size'.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/30731072/146632174-9b4a1022-d205-4ead-855e-76a3dccb7b7a.png">

The correct column name should be 'count'.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/30731072/146632197-7607612a-8388-4383-846b-07ac3d7b522d.png">

```
   group  var1  count
0      1     1      4
1      1     1      4
2      1     1      4
3      1     1      4
4      1     2      1
5      2     1      1
6      2     2      3
7      2     2      3
8      2     2      3
9      2     3      1
```

Seems like a simple enough fix, I'm happy to open a PR if you'ld like

# Relevant Context

- [Link to documentation page](https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions.groupby_agg)
- [Link to exact file to be edited](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/janitor/functions/groupby_agg.py)

**Comment by samukweku** [comment]
@thatlittleboy thanks for the observation! kindly submit a PR for this fix. thanks!
