### ISSUE TITLE
[Security] Workflow tests.yml is using vulnerable action s-weigand/setup-conda

### ISSUE THREAD

**Issue by igibek** [pyjanitor-devs/pyjanitor#965]
The workflow tests.yml is referencing action s-weigand/setup-conda using references v1. However this reference is missing the commit [a30654e576ab9e21a25825bf7a5d5f2a9b95b202](https://github.com/s-weigand/setup-conda/commits/a30654e576ab9e21a25825bf7a5d5f2a9b95b202) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by ericmjl** [comment]
Thank you, @igibek. I plan to move the CI off from s-weigand/setup-conda in favor of conda-incubator/setup-miniconda. I would, however, like to make sure that the lineup of PRs are merged in before we make the switch.

**Comment by Zeroto521** [comment]
This problem have been fixed via #974
