### ISSUE TITLE
[DOC] bin_numeric parameters

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#969]
# Brief Description of Fix

Currently, the docs for `bin_numeric` describes the parameters to be more restrictive than they actually are. According to the pyjanitor docs, `num_bins` is expected to be an Optional[int]:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/30731072/147819958-bf32b65e-a6c4-476b-a2a1-bf936b5fbf0f.png">

However,
pyjanitor's `num_bins` is passed directly into the `bins` parameter of `pd.cut`, as in:
```python
# pyjanitor.bin_numeric src code snippet
df[str(to_column_name)] = pd.cut(df[str(from_column_name)], bins=num_bins)
```
But `bins` parameter of `pd.cut` also accepts list of values / intervalIndex, cf. [pandas docs](https://pandas.pydata.org/pandas-docs/version/1.3.4/reference/api/pandas.cut.html). Which means that at the moment, this is possible:

```python
df = pd.DataFrame(
    np.random.default_rng(42).integers(300, 800, size=(400, 2)),
    columns=['a', 'b'],
).reset_index()

(
    df
    .bin_numeric(from_column_name='a', to_column_name='binned_a', num_bins=[300, 450, 550, 650, 800])
    .head()
)
```
<img width="237" alt="image" src="https://user-images.githubusercontent.com/30731072/147819882-47f7c51e-7f36-4a35-8e3a-764027fec8e7.png">

I see 2 possibilities:
1. Rename `num_bins` to `bins`, deprecate the latter parameter name, and update pyjanitors' docs accordingly to inform users that bins need not necessarily be integer.
2. Keep `num_bins`; in which case, let's check and enforce that the user is passing in an integer (?)

I'm not fond of option 2; I use `pd.cut` with bins specified as a list of cut-values alot in my daily work, so I would prefer to keep this functionality open.

---

In the same vein, how about also allowing **kwargs to be passed in to `bin_numeric` (and pass it directly to `pd.cut` within) so it is more flexible? I don't see a good reason why we are only exposing the `bins`&`labels` parameters to the end user.

To be clear, what I'm proposing is:
```python
def bin_numeric(
    df: pd.DataFrame,
    from_column_name: Hashable,
    to_column_name: Hashable,
    bins: Union[int,...] = 5,  # I'm actually not sure how to annotate this properly at the moment...
    labels: Optional[str] = None,
    **kwargs,
) -> pd.DataFrame:
    if not labels:
        df[str(to_column_name)] = pd.cut(
            df[str(from_column_name)], bins=bins, **kwargs,
        )
    [...snip...]
```

# Relevant Context

- [Link to documentation page](https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions.bin_numeric.bin_numeric)
- [Link to exact file to be edited](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/janitor/functions/bin_numeric.py)

**Comment by samukweku** [comment]
@thatlittleboy I think kwargs is way better/more flexible/less restrictive, and keeps in line with pyjanitor's ease of doing things. besides, we are moving the *worry* to pandas. I'd suggest you submit a PR for this, and add to the changelog as well, so users are aware of this. sniping @ericmjl @pyjanitor-devs/core-devs 

Happy new year by the way !!!! :grin:

**Comment by thatlittleboy** [comment]
Sure, will do. Apart from the kwargs suggestion, can I also take it that we're agreeable to deprecate `num_bins` for `bins`?
