### ISSUE TITLE
Some modules are missing from the top-level import

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#984]
Issue referenced during PR here: https://github.com/pyjanitor-devs/pyjanitor/pull/977#discussion_r781732964

For example, now running:

```python
import janitor as jn
jn.io.read_csvs("")  # throws AttributeError: module 'janitor' has no attribute 'io'
```

Similarly for other modules like biology or timeseries.

**Comment by ericmjl** [comment]
Apart from IO, I think the others were intentionally shielded from the top-level namespace to prevent their imports from running on first import of janitor. Sort of like a namespace shielding. 

That said, I think it's a good idea for the IO module to be top-level, as it'll allow for `jn.read_csvs()` just like `pd.read_csv()` and other IO functions are top-level.

**Comment by thatlittleboy** [comment]
@ericmjl I see! yes, namespace shielding is a good point. Then, I'll just add `io` to top-level imports.
